In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
path='/content/drive/MyDrive/Colab Notebooks/Retail/data/'
gds_a = pd.read_csv(path+'gds_a.csv')
gds_b = pd.read_csv(path+'gds_b.csv')
gds_c = pd.read_csv(path+'gds_c.csv')
gds_d = pd.read_csv(path+'gds_d.csv')
tr_list_a = pd.read_csv(path+'tr_list_a.csv')
tr_list_b = pd.read_csv(path+'tr_list_b.csv')
tr_list_c = pd.read_csv(path+'tr_list_c.csv')
tr_list_d = pd.read_csv(path+'tr_list_d.csv')
tr_dtl_list_a = pd.read_csv(path+'tr_dtl_list_a.csv')
tr_dtl_list_b = pd.read_csv(path+'tr_dtl_list_b.csv')
tr_dtl_list_c = pd.read_csv(path+'tr_dtl_list_c.csv')
tr_dtl_list_d = pd.read_csv(path+'tr_dtl_list_d.csv')

In [10]:
gds_mer = pd.read_csv(path + 'gds_2.csv')
gdsclss_mer = pd.read_csv(path + 'gdsclss_2.csv')

In [ ]:
gdsclss_mer

,CO_CD,STR_CD,GDS_CLSS_CD,GDS_CLSS_NM,GDS_CLSS_LVL_TP,UP_GDS_CLSS_CD,GDS_CLSS_GRP_TP
0,1001294,12018,1,식품,1,0,1
1,1001294,12018,101,가공농산물,2,1,1
2,1001294,12018,10151,가공농산물,3,101,1
3,1001294,12018,10152,김치류,3,101,1
4,1001294,12018,10153,소스,3,101,1
...,...,...,...,...,...,...,...
1134,1002056,0,99,미등록,1,0,1
1135,1002056,0,9979,임시핸디매입등록용,2,99,1
1136,1002056,0,997979,임시핸디매입등록용,3,9979,1
1137,1002056,0,9999,미등록,2,99,1
1138,1002056,0,999999,미등록,3,9999,1

In [ ]:
gds_a

,CO_CD,STR_CD,PLU_CD,GDS_NM,GDS_CLSS_CD,GDS_TP_NM,VEN_CD
0,1001294,12018,1,배송비,999999,배송료,0
1,1001294,12018,2,사은행사쿠폰,999999,배송료,0
2,1001294,12018,91770,코지유리물병,93331,일반,0
3,1001294,12018,91770,크지물병,91701,일반,0
4,1001294,12018,50390427,POM석류,12579,일반,0
...,...,...,...,...,...,...,...
72142,1001294,12018,9999999914157,맥 원형후라이 대(240),93330,일반,0
72143,1001294,12018,9999999914171,맥웰빙원후/8,93330,일반,0
72144,1001294,12018,9999999914393,절구 소소,91701,일반,0
72145,1001294,12018,9999999915079,알뜰Y투라인,91701,일반,0
72146,1001294,12018,9999999915833,맥 웰빙원후 7,91701,일반,0

In [ ]:
tr_dtl_list_a

,SAL_DT,STR_CD,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD,SALE_QTY,SALE_PRC,SALE_AMT,SGDS_DC_TP_NM,SGDS_DC_PRC,SUBTOT_DC_AMT,EVT_DC_AMT,CPON_DC_AMT,SCALES_GDS_TP_NM,GDS_CPON_DC_AMT,BASKET_CPON_DC_AMT
0,20210901,12018,01,3,1,정상판매,1,8801039939499,12301.0,180.0,3000.0,540000.0,할인특매,0.0,0.0,0.0,0.0,일반,0.0,0.0
1,20210901,12018,01,3,2,정상판매,1,8801045312316,12101.0,360.0,1000.0,360000.0,할인특매,0.0,0.0,0.0,0.0,일반,0.0,0.0
2,20210901,12018,01,3,3,정상판매,1,8801045291314,12101.0,360.0,1000.0,360000.0,할인특매,0.0,0.0,0.0,0.0,일반,0.0,0.0
3,20210901,12018,01,3,4,정상판매,1,8803712127018,11363.0,180.0,2700.0,486000.0,할인특매,0.0,0.0,0.0,0.0,일반,0.0,0.0
4,20210901,12018,01,3,5,정상판매,1,8801045890333,12102.0,180.0,9500.0,1710000.0,할인특매,0.0,0.0,0.0,0.0,일반,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5166594,20220901,12018,R1,7,9,정상판매,1,8801052171012,11170.0,1.0,850.0,850.0,할인특매,0.0,0.0,0.0,0.0,일반,0.0,0.0
5166595,20220901,12018,R1,7,10,정상판매,1,8801069221397,12205.0,1.0,4900.0,4380.0,할인특매,520.0,0.0,0.0,0.0,일반,0.0,0.0
5166596,20220901,12018,R1,7,11,정상판매,1,8801075016536,10251.0,1.0,10300.0,7980.0,할인특매,2320.0,0.0,0.0,0.0,일반,0.0,0.0
5166597,20220901,12018,R1,7,12,정상판매,1,8803712301654,10303.0,1.0,13200.0,13200.0,할인특매,0.0,0.0,0.0,0.0,일반,0.0,0.0
5166598,20220901,12018,R1,7,13,정상판매,1,8809389740024,30301.0,1.0,980.0,980.0,할인특매,0.0,0.0,0.0,0.0,일반,0.0,0.0

In [ ]:
a_mer = pd.merge(tr_dtl_list_a[['SAL_DT','SEQ_NO', 'PLU_CD']],gds_a[['PLU_CD', 'GDS_NM']])
a_mer

           SAL_DT  SEQ_NO         PLU_CD                GDS_NM
0        20210901       1  8801039939499           해표 더고소한 파래김
1        20210902       1  8801039939499           해표 더고소한 파래김
2        20210902       1  8801039939499           해표 더고소한 파래김
3        20210902       3  8801039939499           해표 더고소한 파래김
4        20210903       1  8801039939499           해표 더고소한 파래김
...           ...     ...            ...                   ...
5054693  20220901       6  8801045255262    오뚜기 옛날 구수한 끓여먹는누룽지
5054694  20220901       7  8801075014525         사조 살코기참치 안심따개
5054695  20220901       3  8809263421247                쇼핑백(대)
5054696  20220901       4  4987176125293  다우니 엑스퍼트 실내건조 플로럴프레쉬
5054697  20220901       1  8809401602910           프릴베이킹소다허브용기

[5054698 rows x 4 columns]

In [ ]:
dtl_copy = tr_dtl_list_a.copy()

In [ ]:
dtl_mer = pd.merge(dtl_copy, gds_a, how='left', on='PLU_CD')
dtl_mer

,SAL_DT,STR_CD_x,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_CLSS_CD_x,SALE_QTY,...,CPON_DC_AMT,SCALES_GDS_TP_NM,GDS_CPON_DC_AMT,BASKET_CPON_DC_AMT,CO_CD,STR_CD_y,GDS_NM,GDS_CLSS_CD_y,GDS_TP_NM,VEN_CD
0,20210901,12018,01,3,1,정상판매,1,8801039939499,12301.0,180.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,해표 더고소한 파래김,12301.0,일반,16.0
1,20210901,12018,01,3,2,정상판매,1,8801045312316,12101.0,360.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,오뚜기 3분쇠고기카레,12101.0,일반,47.0
2,20210901,12018,01,3,3,정상판매,1,8801045291314,12101.0,360.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,오뚜기 3분쇠고기짜장,12101.0,일반,47.0
3,20210901,12018,01,3,4,정상판매,1,8803712127018,11363.0,180.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,목우촌 뚝심,11363.0,일반,61.0
4,20210901,12018,01,3,5,정상판매,1,8801045890333,12102.0,180.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,오뚜기 맛있는밥기획,12102.0,일반,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5171350,20220901,12018,R1,7,9,정상판매,1,8801052171012,11170.0,1.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,청정원 맛소금,11170.0,일반,35.0
5171351,20220901,12018,R1,7,10,정상판매,1,8801069221397,12205.0,1.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,남양 맛있는우유GT기획,12205.0,일반,2.0
5171352,20220901,12018,R1,7,11,정상판매,1,8801075016536,10251.0,1.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,사조 살코기참치 안심따개,10251.0,일반,16.0
5171353,20220901,12018,R1,7,12,정상판매,1,8803712301654,10303.0,1.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,목우촌 알찬란(특란),10303.0,일반,61.0
5171354,20220901,12018,R1,7,13,정상판매,1,8809389740024,30301.0,1.0,...,0.0,일반,0.0,0.0,1001294.0,12018.0,쌈다시마(팩),30301.0,일반,80.0

In [ ]:
dtl_mer.drop(['CO_CD', 'STR_CD_y', 'GDS_CLSS_CD_x','SGDS_DC_PRC', 'SUBTOT_DC_AMT', 'EVT_DC_AMT', 'CPON_DC_AMT','GDS_CPON_DC_AMT','BASKET_CPON_DC_AMT'], axis=1, inplace=True)
dtl_mer

,SAL_DT,STR_CD_x,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,SALE_QTY,SALE_PRC,SALE_AMT,SGDS_DC_TP_NM,SCALES_GDS_TP_NM,GDS_NM,GDS_CLSS_CD_y,GDS_TP_NM,VEN_CD
0,20210901,12018,01,3,1,정상판매,1,8801039939499,180.0,3000.0,540000.0,할인특매,일반,해표 더고소한 파래김,12301.0,일반,16.0
1,20210901,12018,01,3,2,정상판매,1,8801045312316,360.0,1000.0,360000.0,할인특매,일반,오뚜기 3분쇠고기카레,12101.0,일반,47.0
2,20210901,12018,01,3,3,정상판매,1,8801045291314,360.0,1000.0,360000.0,할인특매,일반,오뚜기 3분쇠고기짜장,12101.0,일반,47.0
3,20210901,12018,01,3,4,정상판매,1,8803712127018,180.0,2700.0,486000.0,할인특매,일반,목우촌 뚝심,11363.0,일반,61.0
4,20210901,12018,01,3,5,정상판매,1,8801045890333,180.0,9500.0,1710000.0,할인특매,일반,오뚜기 맛있는밥기획,12102.0,일반,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5171350,20220901,12018,R1,7,9,정상판매,1,8801052171012,1.0,850.0,850.0,할인특매,일반,청정원 맛소금,11170.0,일반,35.0
5171351,20220901,12018,R1,7,10,정상판매,1,8801069221397,1.0,4900.0,4380.0,할인특매,일반,남양 맛있는우유GT기획,12205.0,일반,2.0
5171352,20220901,12018,R1,7,11,정상판매,1,8801075016536,1.0,10300.0,7980.0,할인특매,일반,사조 살코기참치 안심따개,10251.0,일반,16.0
5171353,20220901,12018,R1,7,12,정상판매,1,8803712301654,1.0,13200.0,13200.0,할인특매,일반,목우촌 알찬란(특란),10303.0,일반,61.0
5171354,20220901,12018,R1,7,13,정상판매,1,8809389740024,1.0,980.0,980.0,할인특매,일반,쌈다시마(팩),30301.0,일반,80.0

In [ ]:
dtl_mer.columns

Index(['SAL_DT', 'STR_CD_x', 'POS_NO', 'TRAN_NO', 'SEQ_NO', 'DESI_CNCL_TP_NM',
       'SALE_RTN_SGN', 'PLU_CD', 'SALE_QTY', 'SALE_PRC', 'SALE_AMT',
       'SGDS_DC_TP_NM', 'SCALES_GDS_TP_NM', 'GDS_NM', 'GDS_CLSS_CD_y',
       'GDS_TP_NM', 'VEN_CD'],
      dtype='object')

In [ ]:
dtl_mer.reindex(columns=['SAL_DT', 'STR_CD_x', 'POS_NO', 'TRAN_NO', 'SEQ_NO', 'DESI_CNCL_TP_NM',
       'SALE_RTN_SGN', 'PLU_CD', 'GDS_NM', 'GDS_CLSS_CD_y', 'SALE_QTY', 'SALE_PRC', 'SALE_AMT',
       'SGDS_DC_TP_NM', 'SCALES_GDS_TP_NM', 
       'GDS_TP_NM', 'VEN_CD'])

,SAL_DT,STR_CD_x,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,GDS_NM,GDS_CLSS_CD_y,SALE_QTY,SALE_PRC,SALE_AMT,SGDS_DC_TP_NM,SCALES_GDS_TP_NM,GDS_TP_NM,VEN_CD
0,20210901,12018,01,3,1,정상판매,1,8801039939499,해표 더고소한 파래김,12301.0,180.0,3000.0,540000.0,할인특매,일반,일반,16.0
1,20210901,12018,01,3,2,정상판매,1,8801045312316,오뚜기 3분쇠고기카레,12101.0,360.0,1000.0,360000.0,할인특매,일반,일반,47.0
2,20210901,12018,01,3,3,정상판매,1,8801045291314,오뚜기 3분쇠고기짜장,12101.0,360.0,1000.0,360000.0,할인특매,일반,일반,47.0
3,20210901,12018,01,3,4,정상판매,1,8803712127018,목우촌 뚝심,11363.0,180.0,2700.0,486000.0,할인특매,일반,일반,61.0
4,20210901,12018,01,3,5,정상판매,1,8801045890333,오뚜기 맛있는밥기획,12102.0,180.0,9500.0,1710000.0,할인특매,일반,일반,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5171350,20220901,12018,R1,7,9,정상판매,1,8801052171012,청정원 맛소금,11170.0,1.0,850.0,850.0,할인특매,일반,일반,35.0
5171351,20220901,12018,R1,7,10,정상판매,1,8801069221397,남양 맛있는우유GT기획,12205.0,1.0,4900.0,4380.0,할인특매,일반,일반,2.0
5171352,20220901,12018,R1,7,11,정상판매,1,8801075016536,사조 살코기참치 안심따개,10251.0,1.0,10300.0,7980.0,할인특매,일반,일반,16.0
5171353,20220901,12018,R1,7,12,정상판매,1,8803712301654,목우촌 알찬란(특란),10303.0,1.0,13200.0,13200.0,할인특매,일반,일반,61.0
5171354,20220901,12018,R1,7,13,정상판매,1,8809389740024,쌈다시마(팩),30301.0,1.0,980.0,980.0,할인특매,일반,일반,80.0

In [ ]:
dtl_mer_copy = dtl_mer.copy()

In [ ]:
dtl_mer_copy.SAL_DT = dtl_mer_copy.SAL_DT.astype('str')
dtl_mer_copy.SAL_DT

0          20210901
1          20210901
2          20210901
3          20210901
4          20210901
             ...
5171350    20220901
5171351    20220901
5171352    20220901
5171353    20220901
5171354    20220901
Name: SAL_DT, Length: 5171355, dtype: object

In [ ]:
dtl_mer_copy.SAL_DT = pd.to_datetime(dtl_mer_copy.SAL_DT)
# dtl_mer_copy.SAL_DT.dt.strftime('%Y/%m/%d')
dtl_mer_copy

,SAL_DT,STR_CD_x,POS_NO,TRAN_NO,SEQ_NO,DESI_CNCL_TP_NM,SALE_RTN_SGN,PLU_CD,SALE_QTY,SALE_PRC,SALE_AMT,SGDS_DC_TP_NM,SCALES_GDS_TP_NM,GDS_NM,GDS_CLSS_CD_y,GDS_TP_NM,VEN_CD
0,2021-09-01,12018,01,3,1,정상판매,1,8801039939499,180.0,3000.0,540000.0,할인특매,일반,해표 더고소한 파래김,12301.0,일반,16.0
1,2021-09-01,12018,01,3,2,정상판매,1,8801045312316,360.0,1000.0,360000.0,할인특매,일반,오뚜기 3분쇠고기카레,12101.0,일반,47.0
2,2021-09-01,12018,01,3,3,정상판매,1,8801045291314,360.0,1000.0,360000.0,할인특매,일반,오뚜기 3분쇠고기짜장,12101.0,일반,47.0
3,2021-09-01,12018,01,3,4,정상판매,1,8803712127018,180.0,2700.0,486000.0,할인특매,일반,목우촌 뚝심,11363.0,일반,61.0
4,2021-09-01,12018,01,3,5,정상판매,1,8801045890333,180.0,9500.0,1710000.0,할인특매,일반,오뚜기 맛있는밥기획,12102.0,일반,47.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5171350,2022-09-01,12018,R1,7,9,정상판매,1,8801052171012,1.0,850.0,850.0,할인특매,일반,청정원 맛소금,11170.0,일반,35.0
5171351,2022-09-01,12018,R1,7,10,정상판매,1,8801069221397,1.0,4900.0,4380.0,할인특매,일반,남양 맛있는우유GT기획,12205.0,일반,2.0
5171352,2022-09-01,12018,R1,7,11,정상판매,1,8801075016536,1.0,10300.0,7980.0,할인특매,일반,사조 살코기참치 안심따개,10251.0,일반,16.0
5171353,2022-09-01,12018,R1,7,12,정상판매,1,8803712301654,1.0,13200.0,13200.0,할인특매,일반,목우촌 알찬란(특란),10303.0,일반,61.0
5171354,2022-09-01,12018,R1,7,13,정상판매,1,8809389740024,1.0,980.0,980.0,할인특매,일반,쌈다시마(팩),30301.0,일반,80.0

In [ ]:
dtl_gr = dtl_mer_copy.groupby(['SAL_DT', 'TRAN_NO', 'GDS_TP_NM'])['GDS_NM'].apply(list).to_frame()
dtl_gr

                                                                         GDS_NM
SAL_DT     TRAN_NO GDS_TP_NM
2021-09-01 1       일반         [*양파(소), *청양고추(소), *대파 1단, *꽈리고추 (500g), *송산포도...
           2       일반         [팽이버섯 1봉, 쌈배추(벌크)1통, *청양고추(소), 가지 1봉, *청양고추 1k...
                   저울상품                                               [한우양지국거리]
           3       일반         [해표 더고소한 파래김, 오뚜기 3분쇠고기카레, 오뚜기 3분쇠고기짜장, 목우촌 뚝심...
                   저울상품                           [양념무뼈닭발, 냉장삼겹살(수입), 찰(완숙)토마토]
...                                                                         ...
2022-09-01 688     일반                                              [홍로사과 10입/봉]
           689     일반                                               [죽염 시린고 치약]
           690     일반                                          [CJ 양념이잘배는찌개두부 ]
           691     일반                                                 [홍로사과/8개]
           692     일반                            [*청상추 1봉, *단호박 1개, 델몬트바나나 1다발]

[445308 rows x 1 columns]

In [ ]:
dtl_gr2 = dtl_mer_copy.groupby(['SAL_DT', 'TRAN_NO'])['GDS_NM'].apply(list).to_frame()
dtl_gr2

                                                               GDS_NM
SAL_DT     TRAN_NO
2021-09-01 1        [*양파(소), *청양고추(소), *대파 1단, *꽈리고추 (500g), *송산포도...
           2        [팽이버섯 1봉, 쌈배추(벌크)1통, *청양고추(소), 가지 1봉, *청양고추 1k...
           3        [해표 더고소한 파래김, 오뚜기 3분쇠고기카레, 오뚜기 3분쇠고기짜장, 목우촌 뚝심...
           4        [**인큐애호박 1개, 진주 천하장사, *백오이 1개, 아삭이고추(2팩), *대파 ...
           5        [칠성사이다, 롯데 그란데아메리카노, 해표 양조간장 , 콘트라베이스디카페인, 롯데 ...
...                                                               ...
2022-09-01 688                                           [홍로사과 10입/봉]
           689                                            [죽염 시린고 치약]
           690                                       [CJ 양념이잘배는찌개두부 ]
           691                                              [홍로사과/8개]
           692                         [*청상추 1봉, *단호박 1개, 델몬트바나나 1다발]

[261216 rows x 1 columns]

In [ ]:
# df_1 = a.reset_index().rename(columns={"index":"PLU_CD"})
# df_1

In [ ]:
dtl_re = dtl_gr.reset_index().rename(columns={"index":"TRAN_NO"})
dtl_re

,SAL_DT,TRAN_NO,GDS_TP_NM,GDS_NM
0,2021-09-01,1,일반,"[*양파(소), *청양고추(소), *대파 1단, *꽈리고추 (500g), *송산포도..."
1,2021-09-01,2,일반,"[팽이버섯 1봉, 쌈배추(벌크)1통, *청양고추(소), 가지 1봉, *청양고추 1k..."
2,2021-09-01,2,저울상품,[한우양지국거리]
3,2021-09-01,3,일반,"[해표 더고소한 파래김, 오뚜기 3분쇠고기카레, 오뚜기 3분쇠고기짜장, 목우촌 뚝심..."
4,2021-09-01,3,저울상품,"[양념무뼈닭발, 냉장삼겹살(수입), 찰(완숙)토마토]"
...,...,...,...,...
445303,2022-09-01,688,일반,[홍로사과 10입/봉]
445304,2022-09-01,689,일반,[죽염 시린고 치약]
445305,2022-09-01,690,일반,[CJ 양념이잘배는찌개두부 ]
445306,2022-09-01,691,일반,[홍로사과/8개]
445307,2022-09-01,692,일반,"[*청상추 1봉, *단호박 1개, 델몬트바나나 1다발]"

In [ ]:
dtl_re2 = dtl_gr2.reset_index().rename(columns={"index":"TRAN_NO"})
dtl_re2

           SAL_DT  TRAN_NO                                             GDS_NM
0      2021-09-01        1  [*양파(소), *청양고추(소), *대파 1단, *꽈리고추 (500g), *송산포도...
1      2021-09-01        2  [팽이버섯 1봉, 쌈배추(벌크)1통, *청양고추(소), 가지 1봉, *청양고추 1k...
2      2021-09-01        3  [해표 더고소한 파래김, 오뚜기 3분쇠고기카레, 오뚜기 3분쇠고기짜장, 목우촌 뚝심...
3      2021-09-01        4  [**인큐애호박 1개, 진주 천하장사, *백오이 1개, 아삭이고추(2팩), *대파 ...
4      2021-09-01        5  [칠성사이다, 롯데 그란데아메리카노, 해표 양조간장 , 콘트라베이스디카페인, 롯데 ...
...           ...      ...                                                ...
261211 2022-09-01      688                                       [홍로사과 10입/봉]
261212 2022-09-01      689                                        [죽염 시린고 치약]
261213 2022-09-01      690                                   [CJ 양념이잘배는찌개두부 ]
261214 2022-09-01      691                                          [홍로사과/8개]
261215 2022-09-01      692                     [*청상추 1봉, *단호박 1개, 델몬트바나나 1다발]

[261216 rows x 3 columns]

In [ ]:
dtl_re[dtl_re['SAL_DT']=='2021-09-01']

        SAL_DT  TRAN_NO                                             GDS_NM
0   2021-09-01        2                          [포카리스웨트, 맛소금 250g, 백설꽃소금]
1   2021-09-01        3                        [무, 맛있는콩 찌개두부, 야채, 무궁화점보비누]
2   2021-09-01        4                                     [피망, 파프리카, 쪽파]
3   2021-09-01        5  [생생우동봉지, 안성탕면멀티, 삼양라면멀티, 퓨어그린물티슈78*10캡, 신라면 멀티...
4   2021-09-01        6                                         [애호박, 애호박]
..         ...      ...                                                ...
99  2021-09-01      102                                               [청과]
100 2021-09-01      103                 [테라500ml, 진로소주16.9, 나가사까, 백설알찬소세지]
101 2021-09-01      104                     [신라면컵 6입, 좋은데이360ml, 델몬트망고1.5]
102 2021-09-01      105  [서울우유카톤, 불가리스 1줄, 스프라이트사이다, 몬스터에너지울트라355ml, 오레...
103 2021-09-01      106                                    [해피홈바퀴에어졸500ml]

[104 rows x 3 columns]

In [ ]:
# from collections import Counter

# dtl_count = Counter(','.join(map(str ,dtl_NM_3['GDS_NM'])).replace('','').split(','))
# dtl_count.most_common()

In [ ]:
dtl_re.GDS_NM

0                                [포카리스웨트, 맛소금 250g, 백설꽃소금]
1                                 [맛있는콩 찌개두부, 야채, 무궁화점보비누]
2                                                      [무]
3                                           [피망, 파프리카, 쪽파]
4        [생생우동봉지, 안성탕면멀티, 삼양라면멀티, 퓨어그린물티슈78*10캡, 신라면 멀티...
                               ...
40834                                     [미에로화이, 1200아맛나]
40835                                        [동원샘물생수, 비식품]
40836         [카스맥주캔, 필라이트후레쉬355ml, 오징어땅콩, 새우깡90g, 종이컵(줄)]
40837                                 [빙그레우유, 파육계장, 옛날육개장]
40838                                                 [대파]
Name: GDS_NM, Length: 40839, dtype: object

In [ ]:
dtl_NM_3 = dtl_re['GDS_NM'].to_frame()
dtl_NM_3

                                                  GDS_NM
0                              [포카리스웨트, 맛소금 250g, 백설꽃소금]
1                            [무, 맛있는콩 찌개두부, 야채, 무궁화점보비누]
2                                         [피망, 파프리카, 쪽파]
3      [생생우동봉지, 안성탕면멀티, 삼양라면멀티, 퓨어그린물티슈78*10캡, 신라면 멀티...
4                                             [애호박, 애호박]
...                                                  ...
35938  [해뜨락맛김치1.2키로, 부산생탁, 예천막걸리, 빙)우유얌딸기, 1200오감자, 오...
35939                                   [미에로화이, 1200아맛나]
35940                                      [동원샘물생수, 비식품]
35941       [카스맥주캔, 필라이트후레쉬355ml, 오징어땅콩, 새우깡90g, 종이컵(줄)]
35942                           [빙그레우유, 파육계장, 옛날육개장, 대파]

[35943 rows x 1 columns]

In [ ]:
dtl_NM_3

                                                  GDS_NM
0                              [포카리스웨트, 맛소금 250g, 백설꽃소금]
1                            [무, 맛있는콩 찌개두부, 야채, 무궁화점보비누]
2                                         [피망, 파프리카, 쪽파]
3      [생생우동봉지, 안성탕면멀티, 삼양라면멀티, 퓨어그린물티슈78*10캡, 신라면 멀티...
4                                             [애호박, 애호박]
...                                                  ...
35938  [해뜨락맛김치1.2키로, 부산생탁, 예천막걸리, 빙)우유얌딸기, 1200오감자, 오...
35939                                   [미에로화이, 1200아맛나]
35940                                      [동원샘물생수, 비식품]
35941       [카스맥주캔, 필라이트후레쉬355ml, 오징어땅콩, 새우깡90g, 종이컵(줄)]
35942                           [빙그레우유, 파육계장, 옛날육개장, 대파]

[35943 rows x 1 columns]

In [ ]:
import itertools

In [ ]:
dtl_apri =dtl_mer_copy[['SAL_DT','TRAN_NO', 'GDS_NM', 'GDS_TP_NM']]
dtl_apri

          SAL_DT  TRAN_NO     GDS_NM GDS_TP_NM
0     2021-09-01        2     포카리스웨트        일반
1     2021-09-01        2   맛소금 250g        일반
2     2021-09-01        2      백설꽃소금        일반
3     2021-09-01        3          무      저울상품
4     2021-09-01        3  맛있는콩 찌개두부        일반
...          ...      ...        ...       ...
91855 2022-09-01      118     종이컵(줄)        일반
91856 2022-09-01      119      빙그레우유        일반
91857 2022-09-01      119       파육계장        일반
91858 2022-09-01      119      옛날육개장        일반
91859 2022-09-01      119         대파      저울상품

[91860 rows x 4 columns]

In [ ]:
def support(df, item_lst):
    return (df[list(item_lst)].sum(axis=1)==len(item_lst)).mean()

In [ ]:
dtl_re2['GDS_NM'] = list(map(','.join, dtl_re2['GDS_NM']))
dtl_re2['GDS_NM']

0                                    포카리스웨트,맛소금 250g,백설꽃소금
1                                     맛있는콩 찌개두부,야채,무궁화점보비누
2                                                        무
3                                               피망,파프리카,쪽파
4        생생우동봉지,안성탕면멀티,삼양라면멀티,퓨어그린물티슈78*10캡,신라면 멀티,코디행복...
                               ...
40834                                        미에로화이,1200아맛나
40835                                           동원샘물생수,비식품
40836               카스맥주캔,필라이트후레쉬355ml,오징어땅콩,새우깡90g,종이컵(줄)
40837                                     빙그레우유,파육계장,옛날육개장
40838                                                   대파
Name: GDS_NM, Length: 40839, dtype: object

In [ ]:
dtl_re2

,SAL_DT,TRAN_NO,GDS_TP_NM,GDS_NM
0,2021-09-01,2,일반,"포카리스웨트,맛소금 250g,백설꽃소금"
1,2021-09-01,3,일반,"맛있는콩 찌개두부,야채,무궁화점보비누"
2,2021-09-01,3,저울상품,무
3,2021-09-01,4,저울상품,"피망,파프리카,쪽파"
4,2021-09-01,5,일반,"생생우동봉지,안성탕면멀티,삼양라면멀티,퓨어그린물티슈78*10캡,신라면 멀티,코디행복..."
...,...,...,...,...
40834,2022-09-01,116,일반,"미에로화이,1200아맛나"
40835,2022-09-01,117,일반,"동원샘물생수,비식품"
40836,2022-09-01,118,일반,"카스맥주캔,필라이트후레쉬355ml,오징어땅콩,새우깡90g,종이컵(줄)"
40837,2022-09-01,119,일반,"빙그레우유,파육계장,옛날육개장"
40838,2022-09-01,119,저울상품,대파

In [ ]:
df2 = dtl_re2['GDS_NM'].to_frame()
df2

                                                  GDS_NM
0                                  포카리스웨트,맛소금 250g,백설꽃소금
1                                   맛있는콩 찌개두부,야채,무궁화점보비누
2                                                      무
3                                             피망,파프리카,쪽파
4      생생우동봉지,안성탕면멀티,삼양라면멀티,퓨어그린물티슈78*10캡,신라면 멀티,코디행복...
...                                                  ...
40834                                      미에로화이,1200아맛나
40835                                         동원샘물생수,비식품
40836             카스맥주캔,필라이트후레쉬355ml,오징어땅콩,새우깡90g,종이컵(줄)
40837                                   빙그레우유,파육계장,옛날육개장
40838                                                 대파

[40839 rows x 1 columns]

In [ ]:
dtl_re

,SAL_DT,TRAN_NO,GDS_TP_NM,GDS_NM
0,2021-09-01,2,일반,"[포카리스웨트, 맛소금 250g, 백설꽃소금]"
1,2021-09-01,3,일반,"[맛있는콩 찌개두부, 야채, 무궁화점보비누]"
2,2021-09-01,3,저울상품,[무]
3,2021-09-01,4,저울상품,"[피망, 파프리카, 쪽파]"
4,2021-09-01,5,일반,"[생생우동봉지, 안성탕면멀티, 삼양라면멀티, 퓨어그린물티슈78*10캡, 신라면 멀티..."
...,...,...,...,...
40834,2022-09-01,116,일반,"[미에로화이, 1200아맛나]"
40835,2022-09-01,117,일반,"[동원샘물생수, 비식품]"
40836,2022-09-01,118,일반,"[카스맥주캔, 필라이트후레쉬355ml, 오징어땅콩, 새우깡90g, 종이컵(줄)]"
40837,2022-09-01,119,일반,"[빙그레우유, 파육계장, 옛날육개장]"
40838,2022-09-01,119,저울상품,[대파]

In [ ]:
dtl_re2

           SAL_DT  TRAN_NO                                             GDS_NM
0      2021-09-01        1  [*양파(소), *청양고추(소), *대파 1단, *꽈리고추 (500g), *송산포도...
1      2021-09-01        2  [팽이버섯 1봉, 쌈배추(벌크)1통, *청양고추(소), 가지 1봉, *청양고추 1k...
2      2021-09-01        3  [해표 더고소한 파래김, 오뚜기 3분쇠고기카레, 오뚜기 3분쇠고기짜장, 목우촌 뚝심...
3      2021-09-01        4  [**인큐애호박 1개, 진주 천하장사, *백오이 1개, 아삭이고추(2팩), *대파 ...
4      2021-09-01        5  [칠성사이다, 롯데 그란데아메리카노, 해표 양조간장 , 콘트라베이스디카페인, 롯데 ...
...           ...      ...                                                ...
261211 2022-09-01      688                                       [홍로사과 10입/봉]
261212 2022-09-01      689                                        [죽염 시린고 치약]
261213 2022-09-01      690                                   [CJ 양념이잘배는찌개두부 ]
261214 2022-09-01      691                                          [홍로사과/8개]
261215 2022-09-01      692                     [*청상추 1봉, *단호박 1개, 델몬트바나나 1다발]

[261216 rows x 3 columns]

In [ ]:
doc = gds_a.GDS_NM
doc

0                   배송비
1                사은행사쿠폰
2                코지유리물병
3                  크지물병
4                 POM석류
              ...
72142    맥 원형후라이 대(240)
72143           맥웰빙원후/8
72144             절구 소소
72145            알뜰Y투라인
72146          맥 웰빙원후 7
Name: GDS_NM, Length: 72147, dtype: object

In [ ]:
!pip install sentence_transformers

In [ ]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.7/dist-packages (3.7)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from nltk) (4.64.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from nltk) (1.1.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.7/dist-packages (from nltk) (2022.6.2)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from nltk) (7.1.2)

In [ ]:
import numpy as np
import itertools

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer
import spacy
from spacy.tokenizer import Tokenizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(doc) # 문장 벡터화 진행

print(tfidf_matrix)

print(tfidf_vectorizer.vocabulary_)

idf = tfidf_vectorizer.idf_
print(dict(zip(tfidf_vectorizer.get_feature_names(), idf)))

In [ ]:
print(doc[[72138, 25139,36565]])

72138    맥 웰빙원후 6
25139    청정원 올리브유
36565    에어윅슬림교체용
Name: GDS_NM, dtype: object

## 데이터 정제

In [ ]:
gds_a_copy = gds_a.copy()
gds_a_copy.head()

     CO_CD  STR_CD    PLU_CD  GDS_NM  GDS_CLSS_CD GDS_TP_NM  VEN_CD
0  1001294   12018         1     배송비       999999       배송료       0
1  1001294   12018         2  사은행사쿠폰       999999       배송료       0
2  1001294   12018     91770  코지유리물병        93331        일반       0
3  1001294   12018     91770    크지물병        91701        일반       0
4  1001294   12018  50390427   POM석류        12579        일반       0

In [ ]:
gds_a_copy.GDS_NM.value_counts()

악세사리             120
모닝다이어리            34
현대)멀티             34
하기스매직팬티           26
멀티플레너다이어리         24
                ...
롯데 레몬워터            1
오렌지포도감귤            1
롯데 립톤복숭아캔          1
롯데 립톤아이스티 복숭아      1
맥 웰빙원후 7           1
Name: GDS_NM, Length: 59453, dtype: int64

In [33]:
gds_a_copy['GDS_NM'] = gds_a_copy['GDS_NM'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")

gds_a_copy

NameError: ignored

In [35]:
gds_mer2 = gds_mer.copy()

In [36]:
gds_mer2['GDS_NM'] = gds_mer2.GDS_NM.str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
gds_mer2

,CO_CD,STR_CD,PLU_CD,GDS_NM,GDS_CLSS_CD,GDS_TP_NM,VEN_CD
0,1001294,12018,1,배송비,999999,배송료,0
1,1001294,12018,2,사은행사쿠폰,999999,배송료,0
2,1001294,12018,91770,코지유리물병,93331,일반,0
3,1001294,12018,91770,크지물병,91701,일반,0
4,1001294,12018,50390427,석류,12579,일반,0
...,...,...,...,...,...,...,...
172730,1002056,168009,9805817760205,포카칩,898989,일반,46
172731,1002056,168009,9808205106111,매입에서등록한상품,997979,일반,30
172732,1002056,168009,9808862878406,월드콘,898989,일반,9
172733,1002056,168009,9880913160015,매입에서등록한상품,997979,일반,34
172734,1002056,168009,99889906,버디 토스트,898989,일반,8989

In [52]:
gds_mer2 = gds_mer2.GDS_NM
gds_mer2

0               배송비
1            사은행사쿠폰
2            코지유리물병
3              크지물병
4                석류
            ...
172730          포카칩
172731    매입에서등록한상품
172732          월드콘
172733    매입에서등록한상품
172734       버디 토스트
Name: GDS_NM, Length: 172735, dtype: object

In [66]:
gds_mer2 = gds_mer2.drop_duplicates()

In [67]:
gds_mer2.to_csv(path+'gds_word.txt', sep = '\t', index = False)

In [68]:
import glob
fnames = glob.glob('/content/drive/MyDrive/Colab Notebooks/Retail/data/gds_word.txt')
for fname in fnames:
    print(fname)

/content/drive/MyDrive/Colab Notebooks/Retail/data/gds_word.txt

In [69]:
for fname in fnames:
    with open(fname, encoding='utf-8') as f:
        docs = [doc.strip() for doc in f]
    print(len(docs), fname.split('/')[-1])

117562 gds_word.txt

In [70]:
for fname in fnames:
    with open(fname, encoding='utf-8') as f:
        docs = [doc.strip() for doc in f]
    print(len(docs), fname.split('/')[-1])

117562 gds_word.txt

In [71]:
class Corpus:
    def __init__(self, fname, iter_sent=False):
        self.fname = fname
        self.iter_sent = iter_sent
        self.doc_length = 0
        self.sent_length = 0
        
    def __iter__(self):
        with open(self.fname, encoding='utf-8') as f:
            for doc in f:
                doc = doc.strip()
                # 핵심영역
                if not self.iter_sent:
                    yield doc
                    continue
                for sent in doc.split('  '):
                    yield sent
                    
    def __len__(self):
        if self.iter_sent:
            if self.sent_length == 0:
                with open(self.fname, encoding='utf-8') as f:
                    for doc in f:
                        self.sent_length += len(doc.strip().split('  '))
            return self.sent_length
        else:
            if self.doc_length == 0:
                with open(self.fname, encoding='utf-8') as f:
                    for num_doc, doc in enumerate(f):
                        continue
                    self.doc_length = (num_doc + 1)
            return self.doc_length

In [72]:
corpus_fname = '/content/drive/MyDrive/Colab Notebooks/Retail/data/gds_word.txt'
corpus = Corpus(corpus_fname, iter_sent=False)

for num_doc, doc in enumerate(corpus):
    if num_doc >= 4: break
    print('%s ...\n'%doc[:100])

GDS_NM ...

배송비 ...

사은행사쿠폰 ...

코지유리물병 ...

In [73]:
%%time
len(corpus)

CPU times: user 31.6 ms, sys: 2.79 ms, total: 34.4 ms
Wall time: 39.4 ms

117562

In [ ]:
# gds_a_copy.GDS_NM.value_counts().loc[lambda x: x > 1]

In [74]:
corpus.iter_sent = True
for num_sent, sent in enumerate(corpus):
    if num_sent >= 30: break
    print('sent %d : %s \n'%(num_sent, sent))

sent 0 : GDS_NM

sent 1 : 배송비

sent 2 : 사은행사쿠폰

sent 3 : 코지유리물병

sent 4 : 크지물병

sent 5 : 석류

sent 6 : 블루베리

sent 7 : 백후추온스

sent 8 : 스니커즈피넛싱글

sent 9 : 등록

sent 10 : 우드락절

sent 11 : 누텔라앤고

sent 12 : 누텔라과자

sent 13 : 펌프

sent 14 : 가스총그리니스

sent 15 : 원더풀아몬드가염

sent 16 : 원더풀피스타치오가염

sent 17 : 원더풀피스타치오무염

sent 18 : 원더풀피스타치오후추

sent 19 : 메이슨레귤러

sent 20 : 메이슨크리스탈

sent 21 : 이메이션

sent 22 : 버드와이저 대캔

sent 23 : 바이스

sent 24 : 바이스플라이어

sent 25 : 바이스뿌라이어

sent 26 : 그린자이언트

sent 27 : 전자식등기구

sent 28 : 스리라차

sent 29 : 쓰리라차

In [75]:
from collections import defaultdict
import sys

corpus.iter_sent = True
max_l_length = 10
min_count = 30

L = defaultdict(lambda: 0)

for num_sent, sent in enumerate(corpus):
    if num_sent % 5000 == 0:
        sys.stdout.write('\risnerting %d sents... ' % num_sent)
    for token in sent.split():
        for e in range(1, min(max_l_length, len(token)) + 1):
            subword = token[:e]
            L[subword] += 1
print('\rinserting subwords into L: done')
print('num subword = %d' % len(L))

L = {subword:freq for subword, freq in L.items() if freq >= min_count}
print('num subword = %d (after pruning with min count %d)' % (len(L), min_count))

inserting subwords into L: done
num subword = 368670
num subword = 1960 (after pruning with min count 30)

In [76]:
print(L)

{'배': 119, '사': 1015, '코': 1057, '크': 1820, '석': 94, '석류': 37, '블': 472, '블루': 231, '블루베': 106, '블루베리': 106, '백': 1207, '스': 2350, '스니': 34, '스니커': 33, '스니커즈': 33, '등': 75, '우': 705, '우드': 42, '누': 177, '가': 640, '가스': 45, '원': 457, '메': 730, '메이': 56, '이': 771, '버': 382, '대': 1738, '바': 1187, '바이': 217, '그': 678, '그린': 274, '전': 278, '전자': 31, '쓰': 33, '엑': 80, '엘': 673, '아': 2169, '엠': 99, '토': 435, '토마': 95, '토마토': 78, '식': 205, '거': 124, '레': 670, '레이': 80, '클': 384, '클래': 75, '클래식': 69, '플': 284, '드': 274, '드라': 49, '드라이': 49, '피': 587, '피넛': 31, '투': 289, '투명': 107, '오': 5753, '크레': 47, '동': 2278, '동서': 455, '암': 68, '내': 197, '내츄': 53, '내츄럴': 52, '클린': 60, '트': 474, '트로': 78, '트로피': 76, '덴': 141, '덴탈': 42, '컴': 81, '허': 450, '허쉬': 161, '리': 1362, '밀': 326, '아이': 619, '청': 2000, '청정': 1208, '청정원': 1025, '스키': 38, '돌': 114, '파': 1044, '파인': 132, '파인애': 73, '파인애플': 72, '밀크': 156, '미': 2140, '미니': 620, '하': 1285, '하인': 33, '하인즈': 33, '구': 569, '구운': 154, '골': 230, '골드': 128, '듀': 139, '듀라': 32, '듀라셀': 31, '디': 357, '알': 473, '지': 231, '프': 1010, '프리': 271, '맛': 494, '질': 116, '질레': 80, '질레트': 80, '마': 1314, '마하': 38, '포': 800, '크리': 373, '크리미': 31, '프레': 194, '판': 74, '콘': 183, '슈': 274, '템': 32, '개': 268, '공': 152, '냉': 243, '우동': 38, '젤': 199, '젤리': 124, '맥': 517, '리고': 40, '땅': 143, '땅콩': 133, '초': 884, '초코': 412, '딸': 281, '딸기': 277, '홀': 62, '연': 224, '에': 911, '에스': 73, '골든': 71, '순': 588, '순한': 77, '순한맛': 30, '중': 383, '매': 1063, '매운': 148, '매운맛': 55, '카': 1023, '카레': 77, '서': 494, '서울': 345, '페': 1005, '크라': 371, '크라운': 346, '이금': 44, '이금기': 44, '시': 459, '기': 292, '타': 274, '타이': 39, '로': 521, '키': 666, '모': 786, '프리미': 158, '프리미엄': 154, '화': 821, '화신': 46, '다': 1030, '다목': 30, '라': 733, '참': 739, '허니': 180, '허니버': 60, '허니버터': 58, '버터': 80, '치': 564, '치즈': 222, '불': 316, '어': 306, '어드': 46, '델': 297, '델몬': 140, '델몬트': 138, '나': 333, '민': 98, '인': 299, '와': 238, '와인': 34, '페이': 33, '스파': 189, '스파게': 58, '스파게티': 58, '하림': 158, '도': 800, '도그': 91, '오리': 1275, '오리지': 185, '오리지날': 72, '케': 401, '쿠': 179, '쿠키': 64, '프링': 101, '프링글': 96, '프링글스': 95, '다우': 192, '다우니': 191, '스팸': 86, '뉴': 441, '뉴트': 70, '에너': 80, '얼': 163, '황': 351, '황금': 54, '레드': 80, '아몬': 143, '아몬드': 142, '도브': 178, '햄': 76, '햄스': 30, '스파클': 47, '스파클링': 43, '개입': 66, '후': 435, '후르': 65, '후르츠': 52, '렌': 48, '렌지': 33, '망': 164, '망고': 118, '자': 1067, '자몽': 50, '쿨': 147, '컨': 69, '퓨': 126, '퓨전': 37, '소': 781, '갈': 150, '갈릭': 46, '스카': 153, '스카치': 69, '포도': 141, '오렌': 151, '오렌지': 151, '부': 508, '부대': 37, '줄': 61, '헤': 208, '세': 562, '까': 145, '샌': 53, '샌드': 45, '에이': 75, '호': 462, '듀얼': 33, '아쿠': 54, '아쿠아': 42, '캔': 164, '캔디': 54, '롯': 3398, '롯데': 2517, '유': 950, '수': 840, '빅': 176, '레몬': 178, '체': 171, '체리': 78, '계': 106, '혼': 89, '혼합': 69, '후라': 55, '포테': 82, '포테이': 34, '포테이토': 34, '채': 47, '반': 166, '수입': 251, '핫': 139, '까르': 35, '스트': 84, '바로': 43, '고': 1290, '할': 54, '하우': 40, '하우스': 30, '슈퍼': 137, '년': 62, '노': 188, '팜': 45, '쉐': 241, '쉐프': 115, '꽁': 41, '큐': 119, '친': 58, '친환': 43, '친환경': 43, '루': 111, '퀴': 45, '항': 60, '항균': 51, '뽀': 392, '뽀로': 294, '뽀로로': 287, '국': 584, '국산': 172, '국산콩': 42, '간': 139, '간편': 53, '아우': 58, '한': 1225, '한라': 32, '사과': 147, '위': 317, '유니': 62, '핸': 181, '핸드': 98, '신': 775, '빨': 69, '철': 70, '단': 452, '동양': 41, '면': 193, '대신': 34, '삼': 1271, '트레': 55, '태': 328, '태양': 50, '종': 385, '종이': 62, '테': 375, '테이': 57, '뚜': 113, '다용': 180, '다용도': 180, '만': 114, '진': 625, '히': 108, '냉동': 151, '피죤': 156, '백설': 871, '농': 793, '농심': 676, '박': 258, '박스': 210, '수프': 42, '수프리': 35, '수프리모': 35, '하이': 232, '예': 207, '백세': 51, '국순': 49, '국순당': 48, '화미': 52, '물': 285, '물티': 38, '물티슈': 38, '번': 160, '번개': 52, '로스': 70, '주': 238, '서주': 51, '민트': 45, '제': 526, '안': 355, '안전': 33, '스타': 189, '해': 2628, '국내': 133, '비': 1280, '팔': 242, '양': 779, '원형': 119, '센': 143, '센서': 30, '목': 335, '목우': 102, '목우촌': 97, '접': 112, '오리온': 696, '롯데초': 42, '롯데초코': 35, '호박': 87, '살': 124, '감': 269, '감자': 180, '봉': 238, '봉지': 70, '조': 405, '고구': 94, '고구마': 93, '밤': 81, '당': 46, '생': 524, '생강': 60, '마늘': 88, '통': 345, '깐': 89, '양파': 57, '적': 64, '실': 289, '영': 207, '영양': 58, '솔': 78, '청양': 41, '애': 667, '홍': 297, '오이': 51, '롱': 103, '엄': 39, '절': 97, '노랑': 32, '팩': 96, '표': 40, '새': 288, '꼬': 272, '꼬마': 82, '병': 85, '가지': 30, '꽃': 283, '쥬': 128, '단호': 55, '단호박': 54, '돼': 136, '돼지': 136, '로즈': 105, '무': 455, '모듬': 46, '비타': 160, '비타민': 47, '쌈': 65, '어린': 66, '신선': 47, '비트': 109, '상': 233, '유기': 191, '유기농': 181, '저': 62, '깻': 31, '추': 74, '찹': 106, '브': 231, '컬': 107, '콜': 137, '콜라': 55, '열': 66, '일': 606, '제주': 115, '동치': 41, '동치미': 40, '섬': 47, '속': 76, '곤': 51, '고추': 130, '방': 121, '막': 42, '보': 517, '보리': 50, '메밀': 61, '머': 181, '곰': 91, '달': 161, '은': 81, '알로': 68, '알로에': 56, '파래': 58, '강': 181, '완': 60, '팥': 38, '옥': 332, '옥수': 117, '옥수수': 117, '찰': 156, '염': 30, '두': 217, '더': 554, '장': 238, '산': 338, '야': 267, '우엉': 32, '도라': 66, '약': 59, '건': 314, '참깨': 54, '들': 129, '콩': 158, '숙': 54, '슬': 174, '슬라': 55, '슬라이': 55, '슬라이스': 40, '도토': 34, '청포': 64, '두부': 38, '순두': 30, '다시': 97, '다시마': 32, '미역': 30, '천': 280, '죽': 93, '야채': 162, '햇': 403, '복': 219, '복숭': 111, '복숭아': 110, '앵': 69, '매실': 54, '국내산': 130, '유자': 39, '피자': 42, '수박': 34, '네': 449, '네오': 106, '캠': 58, '청포도': 55, '가나': 120, '송': 273, '흑': 169, '대추': 30, '금': 146, '설': 129, '황도': 32, '메론': 33, '애플': 88, '스위': 239, '바나': 112, '바나나': 112, '몽': 174, '호두': 77, '크림': 113, '샤': 825, '샤인': 32, '닭': 154, '광': 283, '날': 51, '먹': 43, '멸': 106, '멸치': 91, '문': 94, '바다': 55, '분': 161, '빙': 486, '선': 130, '오징': 203, '오징어': 200, '육': 292, '재': 87, '절단': 30, '중국': 32, '훈': 58, '훈제': 38, '말': 173, '볶': 179, '볶음': 158, '러': 155, '지리': 30, '특': 190, '명': 270, '북': 81, '북어': 42, '황태': 55, '군': 38, '조미': 58, '맥반': 37, '맥반석': 37, '뼈': 39, '쥐': 79, '쥐포': 36, '진미': 43, '김': 376, '왕': 199, '브라': 71, '와사': 43, '와사비': 41, '월': 111, '카카': 109, '카카오': 108, '커': 210, '커피': 135, '파스': 165, '해바': 51, '해바라': 46, '해바라기': 46, '라이': 225, '라이스': 62, '깨': 175, '검': 234, '검정': 73, '둥': 70, '찹쌀': 97, '마카': 36, '웰': 230, '웰빙': 102, '게': 79, '게토': 41, '게토레': 41, '게토레이': 40, '아이스': 235, '자동': 59, '와이': 31, '이지': 127, '오일': 42, '볼': 113, '스마': 118, '스마트': 79, '유리': 67, '엔': 139, '엔젤': 53, '세이': 126, '세이프': 46, '마루': 48, '뿌': 75, '고무': 57, '충': 40, '충전': 30, '바이오': 143, '정': 298, '칼': 319, '칼라': 216, '만능': 52, '쇠': 124, '릴': 51, '우유': 68, '실리': 73, '실리콘': 73, '편': 48, '양면': 67, '테이프': 31, '집': 69, '교': 35, '베': 635, '눈': 36, '손': 219, '손잡': 59, '손잡이': 59, '겨': 106, '겨울': 97, '각': 37, '씽': 71, '씽크': 66, '스텐': 208, '현': 137, '가야': 68, '블랙': 152, '그레': 96, '그레이': 84, '스피': 48, '발': 176, '고급': 115, '돈': 87, '쟈': 39, '면도': 49, '신일': 91, '닥': 157, '닥터': 156, '회': 30, '한우': 243, '새우': 122, '타임': 40, '업': 55, '업소': 32, '모기': 37, '천일': 54, '천일염': 32, '베지': 138, '악': 41, '락': 178, '여': 126, '한일': 70, '점': 58, '점보': 37, '꼬깔': 76, '꼬깔콘': 71, '마가': 52, '마가렛': 40, '마가렛트': 36, '몽쉘': 63, '카스': 174, '카스타': 59, '카스타드': 58, '선물': 30, '베이': 248, '베이비': 90, '김치': 153, '짱': 87, '성': 174, '감귤': 31, '네이': 71, '화이': 522, '화이트': 480, '멘': 51, '멘토': 32, '멘토스': 31, '사각': 199, '비닐': 39, '처': 38, '처음': 36, '처음처': 31, '처음처럼': 31, '참이': 45, '참이슬': 39, '하이트': 85, '샤프': 281, '샤프란': 263, '썬': 296, '베이킹': 67, '베이킹소': 37, '베이킹소다': 37, '벌': 39, '과': 202, '과일': 151, '데': 522, '옻': 38, '캐': 156, '라인': 37, '코스': 50, '코스모': 44, '코스모스': 39, '칸': 146, '번들': 80, '창': 106, '푸': 165, '색': 165, '흰': 31, '큰': 59, '청은': 47, '펭': 53, '펭귄': 42, '액': 169, '샤이': 37, '컵': 188, '음': 46, '입': 245, '샤워': 145, '데톨': 131, '죽염': 70, '페리': 492, '페리오': 477, '옥시': 160, '카프': 48, '카프리': 43, '빼': 175, '빼빼': 150, '빼빼로': 146, '제주감': 35, '제주감귤': 33, '작': 36, '포스': 78, '햇반': 184, '트리': 129, '트리오': 38, '엘라': 199, '엘라스': 120, '엘라스틴': 114, '메디': 272, '메디안': 245, '해태': 1090, '칠': 416, '칠갑': 244, '오뚜': 2184, '오뚜기': 1895, '초코파': 36, '초코파이': 33, '부산': 96, '부산어': 43, '부산어묵': 42, '매일': 357, '쌀': 242, '땡': 53, '아카': 51, '종가': 179, '종가집': 132, '요': 481, '요리': 83, '쁘': 184, '쁘띠': 176, '쁘띠첼': 136, '순창': 97, '하기': 227, '하기스': 204, '차': 119, '순수': 100, '해태아': 49, '해태아이': 34, '데코': 38, '안성': 35, '튜': 34, '폴': 115, '드림': 42, '라임': 34, '싸': 34, '패': 116, '벨': 83, '과일나': 41, '비누': 43, '어린이': 60, '헤어': 91, '케이': 70, '남': 525, '남양': 329, '하트': 63, '나무': 48, '카라': 61, '체크': 36, '핑': 145, '핑크': 128, '기린': 31, '말보': 77, '다이': 143, '다이아': 37, '크리스': 105, '크리스탈': 70, '프린': 58, '소프': 110, '소프트': 104, '너': 75, '파우': 55, '파우치': 40, '동물': 33, '유진': 37, '떡': 77, '장미': 35, '포카': 82, '코카': 207, '코카콜': 61, '코카콜라': 61, '극': 54, '극세': 42, '극세사': 39, '귀': 100, '럭': 67, '도시': 31, '짜': 149, '짜장': 37, '자연': 390, '락스': 42, '직': 106, '낙': 35, '치킨': 118, '햇미': 59, '햇미소': 59, '팝': 79, '팝콘': 34, '현미': 78, '종합': 93, '양념': 136, '스프': 88, '디자': 37, '디자인': 37, '위스': 134, '위스퍼': 104, '엘지': 248, '츄': 83, '츄파': 41, '츄파춥': 33, '츄파춥스': 33, '레쓰': 43, '레쓰비': 43, '크린': 433, '자일': 155, '자일리': 132, '자일리톨': 128, '유한': 180, '맥스': 166, '맥스웰': 50, '올': 287, '올리': 164, '올리브': 142, '올리브유': 45, '스파크': 49, '탈': 44, '건강': 95, '천연': 67, '떡볶': 34, '떡볶이': 34, '우리': 222, '우리쌀': 84, '현대': 48, '덕': 47, '빠': 70, '꿀': 129, '씨': 164, '쫄': 88, '남양맛': 32, '남양맛있': 31, '남양맛있는': 31, '순수한': 36, '삼육': 107, '칠성': 64, '칠성사': 51, '칠성사이': 51, '칠성사이다': 51, '홍삼': 110, '쉐리': 76, '모닝': 193, '진주': 151, '리큐': 105, '냉장': 39, '행': 256, '행사': 55, '스테': 68, '용': 148, '경': 89, '아로': 116, '일반': 102, '황토': 68, '풍': 68, '임': 60, '수저': 31, '베트': 39, '고향': 64, '의': 69, '의성': 45, '압': 34, '맥심': 218, '맥심모': 46, '맥심모카': 46, '휴': 69, '코디': 144, '카누': 99, '쌍': 73, '트롤': 57, '트롤리': 55, '코코': 182, '코코넛': 45, '녹': 212, '롤': 124, '명품': 61, '베스': 39, '베스트': 36, '신라': 60, '신라면': 58, '진라': 38, '진라면': 38, '일회': 50, '일회용': 49, '오가': 83, '맛있': 209, '맛있는': 206, '풀': 855, '풀무': 541, '풀무원': 535, '에코': 72, '위생': 80, '스위트': 187, '퍼': 352, '구름': 51, '앙': 59, '스윗': 31, '무지': 53, '깔': 65, '매직': 163, '담': 179, '프로': 164, '오랄': 117, '오랄비': 99, '스테이': 36, '어드밴': 33, '후레': 144, '후레쉬': 119, '크로': 42, '향': 175, '향균': 52, '샴': 95, '딥': 61, '플레': 77, '플레인': 38, '쏘': 191, '뚝': 46, '계란': 38, '락앤': 67, '락앤락': 67, '믹': 65, '밥': 66, '내추': 63, '내추럴': 63, '온': 302, '멜': 72, '파스텔': 36, '펜': 36, '테크': 222, '갈비': 32, '안심': 97, '국내산돈': 56, '스페': 48, '몬': 97, '본': 130, '요플': 69, '요플레': 69, '좋': 407, '좋은': 398, '좋은느': 274, '좋은느낌': 272, '일가': 37, '크런': 116, '크런치': 48, '퓨어': 61, '하리': 74, '하리보': 70, '해피': 524, '메가': 35, '옷': 31, '웨': 63, '베리': 62, '필': 137, '다크': 33, '켈': 98, '니': 191, '니베': 109, '니베아': 109, '아트': 104, '데오': 49, '데오드': 30, '펄': 53, '립': 104, '모이': 61, '모이스': 48, '키즈': 106, '워': 71, '워터': 39, '리프': 31, '안티': 35, '맨': 35, '파워': 293, '패션': 44, '쿡': 34, '오스': 41, '메탈': 54, '아메': 32, '아메리': 31, '오리지널': 113, '엑스': 45, '카멜': 49, '윈': 41, '메비': 51, '메비우': 51, '메비우스': 51, '스타일': 47, '요구': 33, '요구르': 32, '요구르트': 32, '애니': 134, '바스': 33, '슬림': 81, '바디': 113, '주방': 84, '탑': 42, '초코칩': 34, '카푸': 34, '카푸치': 33, '카푸치노': 32, '킨': 57, '바닐': 73, '바닐라': 72, '키친': 130, '찜': 30, '사골': 42, '구미': 55, '곡': 58, '요거': 62, '요거트': 41, '미라': 45, '미라클': 45, '마시': 52, '킨더': 38, '쉬': 100, '쉬크': 53, '쉐이': 30, '기획': 88, '휴대': 51, '휴대용': 48, '티': 219, '면도기': 32, '변': 58, '바비': 48, '고기': 62, '몬스': 47, '몬스터': 42, '울': 134, '울트': 62, '울트라': 60, '수퍼': 83, '동아': 102, '간장': 40, '세탁': 55, '그레이드': 62, '향기': 71, '라벤': 54, '라벤더': 34, '마이': 239, '포켓': 116, '포켓몬': 75, '연필': 30, '헤드': 47, '마일': 64, '마일드': 64, '참치': 116, '페브': 215, '페브리': 197, '페브리즈': 193, '상쾌': 37, '상쾌한': 33, '팬': 194, '팬틴': 117, '허브': 81, '딥클': 31, '맑': 41, '맑은': 41, '액체': 37, '차량': 48, '리필': 165, '용기': 118, '다우니퍼': 30, '에어': 200, '퍼퓸': 115, '섬유': 32, '미스': 76, '차량용': 33, '아로마': 97, '잇': 35, '센스': 61, '샴푸': 83, '깨끗': 100, '깨끗한': 95, '데일': 72, '데일리': 71, '플라': 69, '밀키': 51, '알파': 35, '갸': 35, '양말': 67, '오레': 69, '오레오': 65, '던': 159, '키티': 166, '칫': 47, '칫솔': 47, '플라워': 46, '녹차': 161, '숯': 58, '찬': 60, '욕': 72, '욕실': 65, '일미': 107, '로얄': 39, '터': 75, '스마일': 35, '논': 39, '가쓰': 65, '가쓰오': 64, '러브': 93, '더블': 189, '매직스': 33, '변기': 37, '플로': 32, '핀': 42, '싱': 62, '쥬시': 59, '헬': 294, '헬로': 181, '헬로키': 111, '헬로키티': 108, '고추장': 36, '쇼': 47, '길': 31, '마스': 65, '마스크': 41, '덴마': 52, '덴마크': 52, '무궁': 75, '무궁화': 74, '액티': 44, '헤이': 40, '헤이즐': 34, '닭가': 47, '닭가슴': 47, '닭가슴살': 43, '캡': 52, '검은': 155, '버블': 113, '초콜': 48, '초콜릿': 43, '원목': 44, '헨': 39, '사이': 35, '옻칠': 31, '레인': 38, '바삭': 42, '옛': 224, '옛날': 210, '나노': 30, '원터': 69, '원터치': 69, '브레': 51, '여행': 44, '여행용': 39, '폴리': 54, '심': 110, '심플': 56, '플러': 51, '플러스': 45, '키세': 48, '키세스': 45, '다회': 32, '다회용': 32, '국화': 30, '세라': 39, '세라믹': 31, '스포': 59, '스포츠': 45, '달콤': 73, '탱': 41, '리퀴': 40, '리퀴드': 39, '퍼실': 50, '웨하': 31, '웨하스': 31, '폰': 92, '카페': 84, '델리': 43, '파르': 79, '이츠': 62, '글': 149, '면사': 58, '면사랑': 58, '스프레': 31, '아미': 49, '빙그': 247, '빙그레': 241, '이츠웰': 55, '라이트': 75, '멀': 230, '멀티': 229, '아라': 48, '아라비': 37, '초극': 32, '초극세': 30, '육우': 166, '잡': 63, '버지': 51, '스크': 36, '선풍': 32, '선풍기': 31, '소스': 34, '신송': 34, '오즈': 39, '월드': 61, '김장': 33, '요술': 40, '베지밀': 129, '서울우': 49, '서울우유': 49, '하나': 63, '하나로': 48, '레종': 57, '아침': 98, '아침에': 46, '리치': 82, '대일': 64, '폰타': 55, '폰타나': 55, '샘': 350, '샘표': 327, '양조': 46, '재래': 53, '불닭': 59, '쇠고': 109, '쇠고기': 109, '비빔': 62, '얼큰': 56, '육개': 43, '육개장': 43, '프렌': 95, '프렌치': 85, '데니': 49, '유성': 31, '숯불': 43, '행복': 149, '행복한': 82, '발아': 36, '제로': 57, '맥스봉': 45, '다담': 62, '켄': 35, '진한': 49, '홈': 583, '비엔': 48, '비엔나': 42, '부대찌': 30, '참그': 83, '참그린': 77, '런': 36, '행복한콩': 59, '오븐': 82, '오곡': 45, '흑미': 30, '강력': 42, '프레시': 81, '프레시안': 37, '사천': 34, '명가': 63, '해찬': 149, '해찬들': 89, '새콤': 65, '새콤달': 50, '새콤달콤': 50, '잘': 91, '하선': 74, '하선정': 68, '산들': 35, '산들애': 32, '컨디': 45, '헛': 35, '헛개': 35, '전통': 39, '다시다': 45, '즉': 40, '즉석': 40, '해물': 109, '우리밀': 35, '도라에': 33, '도라에몽': 33, '불고': 89, '불고기': 88, '그릴': 36, '더건': 105, '더건강': 103, '더건강한': 91, '동그': 37, '삼호': 77, '한입': 156, '맘': 46, '평': 45, '튀': 67, '튀김': 61, '빵': 53, '촉': 44, '촉촉': 37, '김밥': 52, '상하': 54, '제일': 45, '고소': 111, '고소한': 83, '실속': 34, '함': 81, '건강한': 38, '비비': 380, '비비고': 320, '참기': 32, '참기름': 32, '로보': 34, '궁': 44, '궁중': 31, '알래': 38, '알래스': 38, '알래스카': 35, '매콤': 130, '맛고': 37, '햇반컵': 61, '햇반컵반': 52, '진짜': 33, '고메': 138, '직화': 44, '중화': 36, '콤': 56, '쌀국': 32, '쌀국수': 32, '리얼': 126, '스페셜': 37, '폭': 30, '수제': 50, '뿌리': 36, '톡': 34, '소고': 42, '소고기': 41, '누룽': 45, '누룽지': 45, '트리트': 41, '존': 134, '존슨': 94, '뉴트로': 51, '뉴트로지': 33, '뉴트로지나': 33, '아크': 48, '토탈': 54, '존슨즈': 30, '부드': 47, '부드러': 40, '부드러운': 40, '밴': 47, '밴드': 38, '훼': 54, '에센': 30, '클리': 67, '클리어': 46, '삼양': 271, '샤니': 128, '따': 39, '단팥': 36, '굿': 89, '달콤한': 39, '썬키': 145, '썬키스': 101, '썬키스트': 93, '짱구': 58, '라바': 53, '얼초': 30, '에이스': 37, '공룡': 52, '홈런': 38, '홈런볼': 38, '오예': 43, '오예스': 40, '해태오': 42, '롤리': 37, '포키': 31, '해태에': 31, '해태에이': 30, '해태에이스': 30, '부라': 66, '부라보': 59, '앵그': 57, '앵그리': 56, '시크': 67, '시크릿': 66, '햇살': 38, '리틀': 48, '해태자': 34, '스낵': 47, '생생': 69, '바베': 56, '바베큐': 55, '오비': 41, '믹스': 51, '코코몽': 31, '데이': 41, '검은콩': 122, '보드': 52, '롯데비': 46, '클라': 56, '클라우': 47, '클라우드': 47, '별': 90, '베지밀검': 32, '베지밀검은': 30, '포스트': 53, '모카': 65, '제티': 50, '맥심아': 36, '티오': 52, '그래': 37, '그래놀': 35, '그래놀라': 35, '스타벅': 35, '스타벅스': 35, '콜드': 42, '시그': 43, '파티': 38, '도루': 70, '도루코': 69, '터치': 32, '해표': 277, '사조': 295, '광천': 88, '카라멜': 50, '미장': 215, '미장센': 187, '태평': 39, '태평양': 36, '설록': 34, '프라': 45, '해피바': 285, '해피바스': 270, '아모': 36, '려': 226, '려함': 31, '송염': 33, '미쟝': 317, '미쟝센': 305, '댄': 71, '댄트': 55, '댄트롤': 54, '려자': 43, '퍼펙': 60, '퍼펙트': 60, '데미': 65, '미쟝센펄': 30, '일리': 32, '메디안치': 38, '너구': 30, '너구리': 30, '매콤한': 31, '쫄병': 30, '쵸': 55, '쵸코': 44, '웰치': 81, '웰치스': 33, '포테토': 37, '포테토칩': 31, '수미': 31, '수미칩': 30, '지퍼': 66, '에그': 33, '백세카': 39, '백세카레': 39, '삼화': 63, '오즈키': 35, '오즈키친': 35, '정통': 35, '랜': 32, '식물': 42, '라면': 45, '크래': 34, '컵밥': 41, '동원': 1299, '오뚜기옛': 38, '오뚜기옛날': 38, '알뜰': 55, '들기': 34, '들기름': 34, '컬러': 77, '컵누': 48, '컵누들': 47, '오뚜기컵': 34, '스모': 30, '떠': 54, '떠먹': 49, '떠먹는': 48, '또': 76, '오감': 49, '오감자': 33, '모짜': 31, '모짜렐': 30, '모짜렐라': 30, '애경': 314, '순샘': 79, '샤워메': 69, '샤워메이': 65, '샤워메이트': 58, '케라': 236, '케라시': 133, '케라시스': 131, '홈즈': 119, '드럼': 48, '네이처': 49, '살롱': 38, '미세': 35, '린': 35, '퀸': 87, '아이린': 34, '바세': 56, '바세린': 56, '포인': 42, '포인트': 31, '글로': 30, '홍초': 42, '동원참': 43, '동원참치': 38, '동원양': 45, '동원양반': 43, '양반': 133, '리챔': 30, '동원리': 37, '일품': 35, '바른': 32, '개성': 43, '추억': 38, '추억의': 30, '진로': 36, '페리오키': 30, '페리오키즈': 30, '페리오치': 31, '페리오토': 51, '페리오토탈': 49, '실크': 53, '온더': 162, '온더바': 95, '온더바디': 94, '아우라': 51, '아르': 30, '자연퐁': 110, '아미노': 33, '홈스': 196, '홈스타': 188, '리엔': 206, '대나': 61, '대나무': 61, '토디': 59, '토디앙': 58, '냄': 109, '냄새': 91, '냄새먹': 41, '냄새먹는': 41, '참숯': 37, '디펜': 67, '퐁': 34, '테라': 43, '펩': 37, '드봉': 47, '릴리': 43, '죠': 32, '리엔자': 32, '코팅': 33, '파르텔': 63, '사랑': 36, '어벤': 30, '중형': 40, '대형': 55, '특대': 51, '푸드': 39, '쉐프원': 70, '안주': 69, '안주야': 51, '맛선': 42, '맛선생': 40, '카레여': 39, '카레여왕': 39, '대상': 100, '호밍': 32, '호밍스': 32, '비스': 57, '마시는': 34, '청우': 159, '뷰': 32, '초이': 76, '초이스': 64, '네슬': 46, '네슬레': 39, '네스': 110, '네스카': 54, '네스카페': 54, '애견': 42, '칸타': 88, '칸타타': 88, '트로피카': 41, '트로피카나': 40, '펩시': 36, '롯데스': 43, '립톤': 72, '카페라': 31, '카페라떼': 30, '롯데마': 39, '롯데아': 42, '요하': 31, '롯자': 34, '말랑': 57, '왓': 51, '왓따': 50, '목캔': 48, '목캔디': 48, '크런키': 67, '찰떡': 40, '꾸': 38, '리락': 72, '리락쿠': 65, '리락쿠마': 65, '치토': 56, '치토스': 56, '롯데크': 33, '도리': 32, '도리토': 30, '롯데가': 35, '롯가': 30, '롯가나': 30, '헬스': 39, '롯데자': 37, '롯데자일': 34, '롯데자일리': 33, '롯데자일리톨': 33, '애니타': 30, '월드콘': 33, '롯데크런': 30, '쌀로': 47, '쌀로별': 35, '프린세': 44, '프린세스': 44, '아이디': 36, '마블': 31, '소피': 32, '누크': 45, '설레': 40, '설레임': 40, '겨울왕': 82, '겨울왕국': 82, '파워에': 41, '핸디': 58, '아이러': 30, '유동': 39, '대림': 556, '오양': 85, '한성': 248, '모나': 75, '예감': 36, '에프': 68, '삼립': 260, '훼미': 42, '훼미리': 42, '필라': 64, '써': 74, '프렌치카': 41, '프렌치카페': 40, '마키': 33, '불가': 48, '불가리': 47, '불가리스': 41, '삼양라': 33, '삼양라면': 33, '천하': 34, '마미': 55, '켈로': 88, '켈로그': 64, '첵': 30, '환': 72, '환타': 67, '파워에이': 39, '파워에이드': 37, '미닛': 218, '미닛메': 88, '미닛메이': 75, '미닛메이드': 75, '조지': 120, '조지아': 120, '글라': 80, '데미소': 34, '데미소다': 33, '오란': 42, '오란씨': 32, '요맘': 39, '요맘때': 32, '투게': 49, '투게더': 48, '써니': 40, '써니텐': 37, '코코팜': 35, '미니쉘': 31, '마이쮸': 82, '산도': 73, '소가': 39, '자연은': 75, '에쎄': 92, '보루': 45, '던힐': 157, '꼬북': 39, '마켓': 57, '마켓오': 54, '다이제': 40, '고래': 37, '고래밥': 30, '닥터유': 33, '포카칩': 60, '스윙': 38, '스윙칩': 30, '와우': 30, '구구': 57, '필라이': 44, '필라이트': 42, '매일우': 31, '매일바': 43, '매일바이': 35, '매일바이오': 35, '푸르': 48, '푸르밀': 41, '의성마': 39, '의성마늘': 39, '깨끗한나': 71, '깨끗한나라': 70, '팔도': 168, '머거': 68, '머거본': 66, '삼육검': 33, '삼육검은': 33, '옥시크': 34, '옥시크린': 34, '냄새하': 41, '냄새하마': 41, '에어윅': 78, '옥시싹': 37, '옥시싹싹': 37, '파워크': 36, '파워크린': 36, '냄새먹는하': 30, '냄새먹는하마': 30, '데톨핸': 33, '데톨핸드': 33, '소와': 30, '몽고': 49, '크리넥': 187, '크리넥스': 186, '스카트': 47, '디펜드': 55, '좋은느낌울': 30, '화이트시': 61, '화이트시크': 60, '화이트시크릿': 58, '코텍': 56, '애니데': 50, '애니데이': 50, '하기스매': 53, '하기스매직': 52, '하기스매직팬': 31, '하기스매직팬티': 30, '하기스프': 31, '하기스프리': 31, '그린핑': 41, '그린핑거': 41, '말보로': 55, '버지니': 40, '버지니아': 39, '태화': 47, '국제': 64, '파스퇴': 54, '파스퇴르': 54, '대한': 45, '접착': 33, '형': 41, '형광': 33, '모나리': 47, '모나리자': 43, '무선': 33, '아크릴': 35, '화일': 30, '합': 31, '초등': 90, '캐릭': 77, '캐릭터': 51, '단지': 49, '굿프': 30, '모던': 33, '스티': 37, '반짝': 31, '시스': 46, '실버': 34, '크린랩': 75, '크린랲': 38, '순수한면': 30, '릴리안': 30, '삼부': 42, '삼부자': 41, '흡': 34, '에프킬': 51, '에프킬라': 50, '산도깨': 62, '산도깨비': 62, '웅': 119, '웅진': 108, '웅진자': 31, '웅진자연': 31, '던힐파': 33, '던힐파인': 33, '던힐파인컷': 33, '참맛': 34, '고려': 56, '움': 53, '움트': 48, '움트리': 48, '팔리': 42, '팔리아': 42, '팔리아멘': 36, '팔리아멘트': 36, '코멕': 51, '코멕스': 51, '히츠': 43, '초야': 47, '뚜레': 63, '뚜레반': 60, '우일': 48, '씽크대': 36, '해뜨': 57, '해뜨락': 54, '올찬': 53, '리빙': 79, '아트존': 41, '또봇': 61, '대원': 45, '글라스': 53, '디즈': 35, '디즈니': 35, '담터': 113, '과일나라': 35, '신사': 34, '송학': 161, '그루': 50, '흡착': 31, '삼진': 40, '한울': 43, '대영': 37, '맛고을': 32, '키친아': 63, '키친아트': 63, '키아': 37, '풍년': 33, '세신': 67, '퀸센': 41, '퀸센스': 41, '광동': 143, '해피홈': 76, '리체': 38, '리체나': 38, '챕': 35, '챕스': 35, '챕스틱': 35, '아이깨': 37, '아이깨끗': 37, '아이깨끗해': 32, '시스테': 30, '시스테마': 30, '프레시팝': 40, '성경': 113, '글라스락': 35, '댕': 40, '댕기': 39, '꽃남': 50, '꽃을': 43, '꽃을든': 42, '꽃을든남': 42, '꽃을든남자': 41, '홈키': 62, '홈키파': 62, '컴

In [ ]:
L

In [78]:
import numpy as np

def get_cohesion(word):
    # 글자가 아니거가 공백, 혹은 희귀한 단어인 경우
    if(not word) or((word in L) == False):
        return 0.0
    
    if len(word) == 1:
        return 1.0
    
    word_freq = L.get(word, 0)
    base_freq = L.get(word[:1], 0)
    
    if base_freq == 0:
        return 0.0
    else:
        return np.power((word_freq / base_freq), 1/(len(word) - 1))
    
print('오레오 : ', get_cohesion('오레오'))

오레오 :  0.1062941813132467

In [79]:
cohesion_dict = {word: get_cohesion(word) for word in L if len(word)>=2}
len(cohesion_dict)

1470

In [113]:
for word in ['오레', '오레오','', '블루', '블루베', '블루베리', '', '옥수', '옥수수' ]:
    if not word:
        print()
        continue
        
    print('%s = %.3f'%(word, cohesion_dict.get(word, 0.0)))

오레 = 0.012
오레오 = 0.106

블루 = 0.489
블루베 = 0.474
블루베리 = 0.608

옥수 = 0.352
옥수수 = 0.594

In [114]:
def L_tokenize(word):
    if len(word) <= 2:
        return word
    
    score = []
    for e in range(2, min(len(word), max_l_length) + 1):
        subword = word[:e]
        score.append((subword, cohesion_dict.get(subword, 0), e)) # (word, cohesion, length)
        
    return sorted(score, key=lambda x:(x[1], x[2]), reverse=True)[0][0]

for word in cohesion_dict:
    print('%s -> %s \n'%(word, L_tokenize(word)))

석류 -> 석류

블루 -> 블루

블루베 -> 블루

블루베리 -> 블루베리

스니 -> 스니

스니커 -> 스니커

스니커즈 -> 스니커즈

우드 -> 우드

가스 -> 가스

메이 -> 메이

바이 -> 바이

그린 -> 그린

전자 -> 전자

토마 -> 토마

토마토 -> 토마토

레이 -> 레이

클래 -> 클래

클래식 -> 클래식

드라 -> 드라

드라이 -> 드라이

피넛 -> 피넛

투명 -> 투명

크레 -> 크레

동서 -> 동서

내츄 -> 내츄

내츄럴 -> 내츄럴

클린 -> 클린

트로 -> 트로

트로피 -> 트로피

덴탈 -> 덴탈

허쉬 -> 허쉬

아이 -> 아이

청정 -> 청정

청정원 -> 청정원

스키 -> 스키

파인 -> 파인

파인애 -> 파인애

파인애플 -> 파인애플

밀크 -> 밀크

미니 -> 미니

하인 -> 하인

하인즈 -> 하인즈

구운 -> 구운

골드 -> 골드

듀라 -> 듀라

듀라셀 -> 듀라셀

프리 -> 프리

질레 -> 질레

질레트 -> 질레트

마하 -> 마하

크리 -> 크리

크리미 -> 크리

프레 -> 프레

우동 -> 우동

젤리 -> 젤리

리고 -> 리고

땅콩 -> 땅콩

초코 -> 초코

딸기 -> 딸기

에스 -> 에스

골든 -> 골든

순한 -> 순한

순한맛 -> 순한맛

매운 -> 매운

매운맛 -> 매운맛

카레 -> 카레

서울 -> 서울

크라 -> 크라

크라운 -> 크라운

이금 -> 이금

이금기 -> 이금기

타이 -> 타이

프리미 -> 프리미

프리미엄 -> 프리미엄

화신 -> 화신

다목 -> 다목

허니 -> 허니

허니버 -> 허니

허니버터 -> 허니버터

버터 -> 버터

치즈 -> 치즈

어드 -> 어드

델몬 -> 델몬

델몬트 -> 델몬트

와인 -> 와인

페이 -> 페이

스파 -> 스파

스파게 -> 스파게

스파게티 -> 스파게티

하림 -> 하림

도그 -> 도그

오리 -> 오리

오리지 -> 오리

오리지날 -> 오리지날

쿠키 -> 쿠키

프링 -> 프링

프링글 -> 프링글

프링글스 -> 프링글스

다우 -> 다우

다우니 -> 다우니

스팸 -> 스팸

뉴트 -> 뉴트

에너 -> 에너

황금 -> 황금

레드 -> 레드

아몬 -> 아몬

아몬드 -> 아몬드

도브 -> 도브

햄스 -> 햄스

스파클 -> 스파클

스파클링 -> 스파클링

개입 -> 개입

후르 -> 후르

후르츠 -> 후르츠

렌지 -> 렌지

망고 -> 망고

자몽 -> 자몽

퓨전 -> 퓨전

갈릭 -> 갈릭

스카 -> 스카

스카치 -> 스카치

포도 -> 포도

오렌 -> 오렌

오렌지 -> 오렌지

부대 -> 부대

샌드 -> 샌드

에이 -> 에이

듀얼 -> 듀얼

아쿠 -> 아쿠

아쿠아 -> 아쿠아

캔디 -> 캔디

롯데 -> 롯데

레몬 -> 레몬

체리 -> 체리

혼합 -> 혼합

후라 -> 후라

포테 -> 포테

포테이 -> 포테이

포테이토 -> 포테이토

수입 -> 수입

까르 -> 까르

스트 -> 스트

바로 -> 바로

하우 -> 하우

하우스 -> 하우스

슈퍼 -> 슈퍼

쉐프 -> 쉐프

친환 -> 친환

친환경 -> 친환경

항균 -> 항균

뽀로 -> 뽀로

뽀로로 -> 뽀로로

국산 -> 국산

국산콩 -> 국산

간편 -> 간편

아우 -> 아우

한라 -> 한라

사과 -> 사과

유니 -> 유니

핸드 -> 핸드

동양 -> 동양

대신 -> 대신

트레 -> 트레

태양 -> 태양

종이 -> 종이

테이 -> 테이

다용 -> 다용

다용도 -> 다용도

냉동 -> 냉동

피죤 -> 피죤

백설 -> 백설

농심 -> 농심

박스 -> 박스

수프 -> 수프

수프리 -> 수프리

수프리모 -> 수프리모

하이 -> 하이

백세 -> 백세

국순 -> 국순

국순당 -> 국순당

화미 -> 화미

물티 -> 물티

물티슈 -> 물티슈

번개 -> 번개

로스 -> 로스

서주 -> 서주

민트 -> 민트

안전 -> 안전

스타 -> 스타

국내 -> 국내

원형 -> 원형

센서 -> 센서

목우 -> 목우

목우촌 -> 목우촌

오리온 -> 오리온

롯데초 -> 롯데

롯데초코 -> 롯데

호박 -> 호박

감자 -> 감자

봉지 -> 봉지

고구 -> 고구

고구마 -> 고구마

생강 -> 생강

마늘 -> 마늘

양파 -> 양파

영양 -> 영양

청양 -> 청양

오이 -> 오이

노랑 -> 노랑

꼬마 -> 꼬마

가지 -> 가지

단호 -> 단호

단호박 -> 단호박

돼지 -> 돼지

로즈 -> 로즈

모듬 -> 모듬

비타 -> 비타

비타민 -> 비타민

어린 -> 어린

신선 -> 신선

비트 -> 비트

유기 -> 유기

유기농 -> 유기농

콜라 -> 콜라

제주 -> 제주

동치 -> 동치

동치미 -> 동치미

고추 -> 고추

보리 -> 보리

메밀 -> 메밀

알로 -> 알로

알로에 -> 알로에

파래 -> 파래

옥수 -> 옥수

옥수수 -> 옥수수

우엉 -> 우엉

도라 -> 도라

참깨 -> 참깨

슬라 -> 슬라

슬라이 -> 슬라이

슬라이스 -> 슬라이스

도토 -> 도토

청포 -> 청포

두부 -> 두부

순두 -> 순두

다시 -> 다시

다시마 -> 다시마

미역 -> 미역

야채 -> 야채

복숭 -> 복숭

복숭아 -> 복숭아

매실 -> 매실

국내산 -> 국내산

유자 -> 유자

피자 -> 피자

수박 -> 수박

네오 -> 네오

청포도 -> 청포도

가나 -> 가나

대추 -> 대추

황도 -> 황도

메론 -> 메론

애플 -> 애플

스위 -> 스위

바나 -> 바나

바나나 -> 바나나

호두 -> 호두

크림 -> 크림

샤인 -> 샤인

멸치 -> 멸치

바다 -> 바다

오징 -> 오징

오징어 -> 오징어

절단 -> 절단

중국 -> 중국

훈제 -> 훈제

볶음 -> 볶음

지리 -> 지리

북어 -> 북어

황태 -> 황태

조미 -> 조미

맥반 -> 맥반

맥반석 -> 맥반석

쥐포 -> 쥐포

진미 -> 진미

브라 -> 브라

와사 -> 와사

와사비 -> 와사비

카카 -> 카카

카카오 -> 카카오

커피 -> 커피

파스 -> 파스

해바 -> 해바

해바라 -> 해바라

해바라기 -> 해바라기

라이 -> 라이

라이스 -> 라이

검정 -> 검정

찹쌀 -> 찹쌀

마카 -> 마카

웰빙 -> 웰빙

게토 -> 게토

게토레 -> 게토레

게토레이 -> 게토레이

아이스 -> 아이스

자동 -> 자동

와이 -> 와이

이지 -> 이지

오일 -> 오일

스마 -> 스마

스마트 -> 스마트

유리 -> 유리

엔젤 -> 엔젤

세이 -> 세이

세이프 -> 세이프

마루 -> 마루

고무 -> 고무

충전 -> 충전

바이오 -> 바이오

칼라 -> 칼라

만능 -> 만능

우유 -> 우유

실리 -> 실리

실리콘 -> 실리콘

양면 -> 양면

테이프 -> 테이프

손잡 -> 손잡

손잡이 -> 손잡이

겨울 -> 겨울

씽크 -> 씽크

스텐 -> 스텐

가야 -> 가야

블랙 -> 블랙

그레 -> 그레

그레이 -> 그레이

스피 -> 스피

고급 -> 고급

면도 -> 면도

신일 -> 신일

닥터 -> 닥터

한우 -> 한우

새우 -> 새우

타임 -> 타임

업소 -> 업소

모기 -> 모기

천일 -> 천일

천일염 -> 천일염

베지 -> 베지

한일 -> 한일

점보 -> 점보

꼬깔 -> 꼬깔

꼬깔콘 -> 꼬깔콘

마가 -> 마가

마가렛 -> 마가렛

마가렛트 -> 마가렛트

몽쉘 -> 몽쉘

카스 -> 카스

카스타 -> 카스타

카스타드 -> 카스타드

선물 -> 선물

베이 -> 베이

베이비 -> 베이

김치 -> 김치

감귤 -> 감귤

네이 -> 네이

화이 -> 화이

화이트 -> 화이트

멘토 -> 멘토

멘토스 -> 멘토스

사각 -> 사각

비닐 -> 비닐

처음 -> 처음

처음처 -> 처음

처음처럼 -> 처음

참이 -> 참이

참이슬 -> 참이슬

하이트 -> 하이트

샤프 -> 샤프

샤프란 -> 샤프란

베이킹 -> 베이

베이킹소 -> 베이

베이킹소다 -> 베이킹소다

과일 -> 과일

라인 -> 라인

코스 -> 코스

코스모 -> 코스모

코스모스 -> 코스모스

번들 -> 번들

청은 -> 청은

펭귄 -> 펭귄

샤이 -> 샤이

샤워 -> 샤워

데톨 -> 데톨

죽염 -> 죽염

페리 -> 페리

페리오 -> 페리오

옥시 -> 옥시

카프 -> 카프

카프리 -> 카프리

빼빼 -> 빼빼

빼빼로 -> 빼빼로

제주감 -> 제주감

제주감귤 -> 제주감귤

포스 -> 포스

햇반 -> 햇반

트리 -> 트리

트리오 -> 트리오

엘라 -> 엘라

엘라스 -> 엘라스

엘라스틴 -> 엘라스틴

메디 -> 메디

메디안 -> 메디안

해태 -> 해태

칠갑 -> 칠갑

오뚜 -> 오뚜

오뚜기 -> 오뚜기

초코파 -> 초코

초코파이 -> 초코

부산 -> 부산

부산어 -> 부산어

부산어묵 -> 부산어묵

매일 -> 매일

아카 -> 아카

종가 -> 종가

종가집 -> 종가집

요리 -> 요리

쁘띠 -> 쁘띠

쁘띠첼 -> 쁘띠

순창 -> 순창

하기 -> 하기

하기스 -> 하기스

순수 -> 순수

해태아 -> 해태

해태아이 -> 해태

데코 -> 데코

안성 -> 안성

드림 -> 드림

라임 -> 라임

과일나 -> 과일

비누 -> 비누

어린이 -> 어린이

헤어 -> 헤어

케이 -> 케이

남양 -> 남양

하트 -> 하트

나무 -> 나무

카라 -> 카라

체크 -> 체크

핑크 -> 핑크

기린 -> 기린

말보 -> 말보

다이 -> 다이

다이아 -> 다이아

크리스 -> 크리스

크리스탈 -> 크리스탈

프린 -> 프린

소프 -> 소프

소프트 -> 소프트

파우 -> 파우

파우치 -> 파우치

동물 -> 동물

유진 -> 유진

장미 -> 장미

포카 -> 포카

코카 -> 코카

코카콜 -> 코카콜

코카콜라 -> 코카콜라

극세 -> 극세

극세사 -> 극세사

도시 -> 도시

짜장 -> 짜장

자연 -> 자연

락스 -> 락스

치킨 -> 치킨

햇미 -> 햇미

햇미소 -> 햇미소

팝콘 -> 팝콘

현미 -> 현미

종합 -> 종합

양념 -> 양념

스프 -> 스프

디자 -> 디자

디자인 -> 디자인

위스 -> 위스

위스퍼 -> 위스퍼

엘지 -> 엘지

츄파 -> 츄파

츄파춥 -> 츄파춥

츄파춥스 -> 츄파춥스

레쓰 -> 레쓰

레쓰비 -> 레쓰비

크린 -> 크린

자일 -> 자일

자일리 -> 자일리

자일리톨 -> 자일리톨

유한 -> 유한

맥스 -> 맥스

맥스웰 -> 맥스

올리 -> 올리

올리브 -> 올리브

올리브유 -> 올리브

스파크 -> 스파크

건강 -> 건강

천연 -> 천연

떡볶 -> 떡볶

떡볶이 -> 떡볶이

우리 -> 우리

우리쌀 -> 우리쌀

현대 -> 현대

남양맛 -> 남양

남양맛있 -> 남양

남양맛있는 -> 남양

순수한 -> 순수한

삼육 -> 삼육

칠성 -> 칠성

칠성사 -> 칠성사

칠성사이 -> 칠성사이

칠성사이다 -> 칠성사이다

홍삼 -> 홍삼

쉐리 -> 쉐리

모닝 -> 모닝

진주 -> 진주

리큐 -> 리큐

냉장 -> 냉장

행사 -> 행사

스테 -> 스테

아로 -> 아로

일반 -> 일반

황토 -> 황토

수저 -> 수저

베트 -> 베트

고향 -> 고향

의성 -> 의성

맥심 -> 맥심

맥심모 -> 맥심

맥심모카 -> 맥심모카

코디 -> 코디

카누 -> 카누

트롤 -> 트롤

트롤리 -> 트롤리

코코 -> 코코

코코넛 -> 코코넛

명품 -> 명품

베스 -> 베스

베스트 -> 베스트

신라 -> 신라

신라면 -> 신라면

진라 -> 진라

진라면 -> 진라면

일회 -> 일회

일회용 -> 일회용

오가 -> 오가

맛있 -> 맛있

맛있는 -> 맛있는

풀무 -> 풀무

풀무원 -> 풀무원

에코 -> 에코

위생 -> 위생

스위트 -> 스위트

구름 -> 구름

스윗 -> 스윗

무지 -> 무지

매직 -> 매직

프로 -> 프로

오랄 -> 오랄

오랄비 -> 오랄비

스테이 -> 스테이

어드밴 -> 어드밴

후레 -> 후레

후레쉬 -> 후레쉬

크로 -> 크로

향균 -> 향균

플레 -> 플레

플레인 -> 플레인

계란 -> 계란

락앤 -> 락앤

락앤락 -> 락앤락

내추 -> 내추

내추럴 -> 내추럴

파스텔 -> 파스텔

테크 -> 테크

갈비 -> 갈비

안심 -> 안심

국내산돈 -> 국내산

스페 -> 스페

요플 -> 요플

요플레 -> 요플레

좋은 -> 좋은

좋은느 -> 좋은

좋은느낌 -> 좋은

일가 -> 일가

크런 -> 크런

크런치 -> 크런치

퓨어 -> 퓨어

하리 -> 하리

하리보 -> 하리보

해피 -> 해피

메가 -> 메가

베리 -> 베리

다크 -> 다크

니베 -> 니베

니베아 -> 니베아

아트 -> 아트

데오 -> 데오

데오드 -> 데오드

모이 -> 모이

모이스 -> 모이스

키즈 -> 키즈

워터 -> 워터

리프 -> 리프

안티 -> 안티

파워 -> 파워

패션 -> 패션

오스 -> 오스

메탈 -> 메탈

아메 -> 아메

아메리 -> 아메리

오리지널 -> 오리지널

엑스 -> 엑스

카멜 -> 카멜

메비 -> 메비

메비우 -> 메비우

메비우스 -> 메비우스

스타일 -> 스타일

요구 -> 요구

요구르 -> 요구르

요구르트 -> 요구르트

애니 -> 애니

바스 -> 바스

슬림 -> 슬림

바디 -> 바디

주방 -> 주방

초코칩 -> 초코

카푸 -> 카푸

카푸치 -> 카푸치

카푸치노 -> 카푸치노

바닐 -> 바닐

바닐라 -> 바닐라

키친 -> 키친

사골 -> 사골

구미 -> 구미

요거 -> 요거

요거트 -> 요거트

미라 -> 미라

미라클 -> 미라클

마시 -> 마시

킨더 -> 킨더

쉬크 -> 쉬크

쉐이 -> 쉐이

기획 -> 기획

휴대 -> 휴대

휴대용 -> 휴대용

면도기 -> 면도기

바비 -> 바비

고기 -> 고기

몬스 -> 몬스

몬스터 -> 몬스터

울트 -> 울트

울트라 -> 울트라

수퍼 -> 수퍼

동아 -> 동아

간장 -> 간장

세탁 -> 세탁

그레이드 -> 그레이드

향기 -> 향기

라벤 -> 라벤

라벤더 -> 라벤더

마이 -> 마이

포켓 -> 포켓

포켓몬 -> 포켓몬

연필 -> 연필

헤드 -> 헤드

마일 -> 마일

마일드 -> 마일드

참치 -> 참치

페브 -> 페브

페브리 -> 페브리

페브리즈 -> 페브리즈

상쾌 -> 상쾌

상쾌한 -> 상쾌한

팬틴 -> 팬틴

허브 -> 허브

딥클 -> 딥클

맑은 -> 맑은

액체 -> 액체

차량 -> 차량

리필 -> 리필

용기 -> 용기

다우니퍼 -> 다우니

에어 -> 에어

퍼퓸 -> 퍼퓸

섬유 -> 섬유

미스 -> 미스

차량용 -> 차량용

아로마 -> 아로마

센스 -> 센스

샴푸 -> 샴푸

깨끗 -> 깨끗

깨끗한 -> 깨끗한

데일 -> 데일

데일리 -> 데일리

플라 -> 플라

밀키 -> 밀키

알파 -> 알파

양말 -> 양말

오레 -> 오레

오레오 -> 오레오

키티 -> 키티

칫솔 -> 칫솔

플라워 -> 플라워

녹차 -> 녹차

욕실 -> 욕실

일미 -> 일미

로얄 -> 로얄

스마일 -> 스마일

가쓰 -> 가쓰

가쓰오 -> 가쓰오

러브 -> 러브

더블 -> 더블

매직스 -> 매직스

변기 -> 변기

플로 -> 플로

쥬시 -> 쥬시

헬로 -> 헬로

헬로키 -> 헬로

헬로키티 -> 헬로키티

고추장 -> 고추장

마스 -> 마스

마스크 -> 마스크

덴마 -> 덴마

덴마크 -> 덴마크

무궁 -> 무궁

무궁화 -> 무궁화

액티 -> 액티

헤이 -> 헤이

헤이즐 -> 헤이즐

닭가 -> 닭가

닭가슴 -> 닭가슴

닭가슴살 -> 닭가슴살

검은 -> 검은

버블 -> 버블

초콜 -> 초콜

초콜릿 -> 초콜릿

원목 -> 원목

사이 -> 사이

옻칠 -> 옻칠

레인 -> 레인

바삭 -> 바삭

옛날 -> 옛날

나노 -> 나노

원터 -> 원터

원터치 -> 원터치

브레 -> 브레

여행 -> 여행

여행용 -> 여행용

폴리 -> 폴리

심플 -> 심플

플러 -> 플러

플러스 -> 플러스

키세 -> 키세

키세스 -> 키세스

다회 -> 다회

다회용 -> 다회용

국화 -> 국화

세라 -> 세라

세라믹 -> 세라믹

스포 -> 스포

스포츠 -> 스포츠

달콤 -> 달콤

리퀴 -> 리퀴

리퀴드 -> 리퀴드

퍼실 -> 퍼실

웨하 -> 웨하

웨하스 -> 웨하스

카페 -> 카페

델리 -> 델리

파르 -> 파르

이츠 -> 이츠

면사 -> 면사

면사랑 -> 면사랑

스프레 -> 스프레

아미 -> 아미

빙그 -> 빙그

빙그레 -> 빙그레

이츠웰 -> 이츠웰

라이트 -> 라이트

멀티 -> 멀티

아라 -> 아라

아라비 -> 아라비

초극 -> 초극

초극세 -> 초극세

육우 -> 육우

버지 -> 버지

스크 -> 스크

선풍 -> 선풍

선풍기 -> 선풍기

소스 -> 소스

신송 -> 신송

오즈 -> 오즈

월드 -> 월드

김장 -> 김장

요술 -> 요술

베지밀 -> 베지밀

서울우 -> 서울

서울우유 -> 서울

하나 -> 하나

하나로 -> 하나로

레종 -> 레종

아침 -> 아침

아침에 -> 아침에

리치 -> 리치

대일 -> 대일

폰타 -> 폰타

폰타나 -> 폰타나

샘표 -> 샘표

양조 -> 양조

재래 -> 재래

불닭 -> 불닭

쇠고 -> 쇠고

쇠고기 -> 쇠고기

비빔 -> 비빔

얼큰 -> 얼큰

육개 -> 육개

육개장 -> 육개장

프렌 -> 프렌

프렌치 -> 프렌치

데니 -> 데니

유성 -> 유성

숯불 -> 숯불

행복 -> 행복

행복한 -> 행복

발아 -> 발아

제로 -> 제로

맥스봉 -> 맥스

다담 -> 다담

진한 -> 진한

비엔 -> 비엔

비엔나 -> 비엔나

부대찌 -> 부대찌

참그 -> 참그

참그린 -> 참그린

행복한콩 -> 행복한콩

오븐 -> 오븐

오곡 -> 오곡

흑미 -> 흑미

강력 -> 강력

프레시 -> 프레시

프레시안 -> 프레시안

사천 -> 사천

명가 -> 명가

해찬 -> 해찬

해찬들 -> 해찬들

새콤 -> 새콤

새콤달 -> 새콤달

새콤달콤 -> 새콤달콤

하선 -> 하선

하선정 -> 하선정

산들 -> 산들

산들애 -> 산들애

컨디 -> 컨디

헛개 -> 헛개

전통 -> 전통

다시다 -> 다시다

즉석 -> 즉석

해물 -> 해물

우리밀 -> 우리

도라에 -> 도라에

도라에몽 -> 도라에몽

불고 -> 불고

불고기 -> 불고기

그릴 -> 그릴

더건 -> 더건

더건강 -> 더건강

더건강한 -> 더건강한

동그 -> 동그

삼호 -> 삼호

한입 -> 한입

튀김 -> 튀김

촉촉 -> 촉촉

김밥 -> 김밥

상하 -> 상하

제일 -> 제일

고소 -> 고소

고소한 -> 고소한

실속 -> 실속

건강한 -> 건강한

비비 -> 비비

비비고 -> 비비고

참기 -> 참기

참기름 -> 참기름

로보 -> 로보

궁중 -> 궁중

알래 -> 알래

알래스 -> 알래스

알래스카 -> 알래스카

매콤 -> 매콤

맛고 -> 맛고

햇반컵 -> 햇반

햇반컵반 -> 햇반컵반

진짜 -> 진짜

고메 -> 고메

직화 -> 직화

중화 -> 중화

쌀국 -> 쌀국

쌀국수 -> 쌀국수

리얼 -> 리얼

스페셜 -> 스페셜

수제 -> 수제

뿌리 -> 뿌리

소고 -> 소고

소고기 -> 소고기

누룽 -> 누룽

누룽지 -> 누룽지

트리트 -> 트리트

존슨 -> 존슨

뉴트로 -> 뉴트로

뉴트로지 -> 뉴트로지

뉴트로지나 -> 뉴트로지나

아크 -> 아크

토탈 -> 토탈

존슨즈 -> 존슨

부드 -> 부드

부드러 -> 부드러

부드러운 -> 부드러운

밴드 -> 밴드

에센 -> 에센

클리 -> 클리

클리어 -> 클리어

삼양 -> 삼양

샤니 -> 샤니

단팥 -> 단팥

달콤한 -> 달콤한

썬키 -> 썬키

썬키스 -> 썬키스

썬키스트 -> 썬키스트

짱구 -> 짱구

라바 -> 라바

얼초 -> 얼초

에이스 -> 에이스

공룡 -> 공룡

홈런 -> 홈런

홈런볼 -> 홈런볼

오예 -> 오예

오예스 -> 오예스

해태오 -> 해태

롤리 -> 롤리

포키 -> 포키

해태에 -> 해태

해태에이 -> 해태

해태에이스 -> 해태

부라 -> 부라

부라보 -> 부라보

앵그 -> 앵그

앵그리 -> 앵그리

시크 -> 시크

시크릿 -> 시크릿

햇살 -> 햇살

리틀 -> 리틀

해태자 -> 해태

스낵 -> 스낵

생생 -> 생생

바베 -> 바베

바베큐 -> 바베큐

오비 -> 오비

믹스 -> 믹스

코코몽 -> 코코

데이 -> 데이

검은콩 -> 검은콩

보드 -> 보드

롯데비 -> 롯데

클라 -> 클라

클라우 -> 클라우

클라우드 -> 클라우드

베지밀검 -> 베지밀

베지밀검은 -> 베지밀검은

포스트 -> 포스트

모카 -> 모카

제티 -> 제티

맥심아 -> 맥심

티오 -> 티오

그래 -> 그래

그래놀 -> 그래놀

그래놀라 -> 그래놀라

스타벅 -> 스타벅

스타벅스 -> 스타벅스

콜드 -> 콜드

시그 -> 시그

파티 -> 파티

도루 -> 도루

도루코 -> 도루코

터치 -> 터치

해표 -> 해표

사조 -> 사조

광천 -> 광천

카라멜 -> 카라멜

미장 -> 미장

미장센 -> 미장센

태평 -> 태평

태평양 -> 태평양

설록 -> 설록

프라 -> 프라

해피바 -> 해피바

해피바스 -> 해피바스

아모 -> 아모

려함 -> 려함

송염 -> 송염

미쟝 -> 미쟝

미쟝센 -> 미쟝센

댄트 -> 댄트

댄트롤 -> 댄트롤

려자 -> 려자

퍼펙 -> 퍼펙

퍼펙트 -> 퍼펙트

데미 -> 데미

미쟝센펄 -> 미쟝센

일리 -> 일리

메디안치 -> 메디안

너구 -> 너구

너구리 -> 너구리

매콤한 -> 매콤한

쫄병 -> 쫄병

쵸코 -> 쵸코

웰치 -> 웰치

웰치스 -> 웰치스

포테토 -> 포테토

포테토칩 -> 포테토칩

수미 -> 수미

수미칩 -> 수미칩

지퍼 -> 지퍼

에그 -> 에그

백세카 -> 백세카

백세카레 -> 백세카레

삼화 -> 삼화

오즈키 -> 오즈키

오즈키친 -> 오즈키친

정통 -> 정통

식물 -> 식물

라면 -> 라면

크래 -> 크래

컵밥 -> 컵밥

동원 -> 동원

오뚜기옛 -> 오뚜기

오뚜기옛날 -> 오뚜기

알뜰 -> 알뜰

들기 -> 들기

들기름 -> 들기름

컬러 -> 컬러

컵누 -> 컵누

컵누들 -> 컵누들

오뚜기컵 -> 오뚜기

스모 -> 스모

떠먹 -> 떠먹

떠먹는 -> 떠먹는

오감 -> 오감

오감자 -> 오감자

모짜 -> 모짜

모짜렐 -> 모짜렐

모짜렐라 -> 모짜렐라

애경 -> 애경

순샘 -> 순샘

샤워메 -> 샤워메

샤워메이 -> 샤워메이

샤워메이트 -> 샤워메이트

케라 -> 케라

케라시 -> 케라

케라시스 -> 케라시스

홈즈 -> 홈즈

드럼 -> 드럼

네이처 -> 네이처

살롱 -> 살롱

미세 -> 미세

아이린 -> 아이

바세 -> 바세

바세린 -> 바세린

포인 -> 포인

포인트 -> 포인트

글로 -> 글로

홍초 -> 홍초

동원참 -> 동원

동원참치 -> 동원

동원양 -> 동원

동원양반 -> 동원

양반 -> 양반

리챔 -> 리챔

동원리 -> 동원

일품 -> 일품

바른 -> 바른

개성 -> 개성

추억 -> 추억

추억의 -> 추억의

진로 -> 진로

페리오키 -> 페리오

페리오키즈 -> 페리오

페리오치 -> 페리오

페리오토 -> 페리오

페리오토탈 -> 페리오

실크 -> 실크

온더 -> 온더

온더바 -> 온더바

온더바디 -> 온더바디

아우라 -> 아우라

아르 -> 아르

자연퐁 -> 자연

아미노 -> 아미노

홈스 -> 홈스

홈스타 -> 홈스타

리엔 -> 리엔

대나 -> 대나

대나무 -> 대나무

토디 -> 토디

토디앙 -> 토디앙

냄새 -> 냄새

냄새먹 -> 냄새

냄새먹는 -> 냄새

참숯 -> 참숯

디펜 -> 디펜

테라 -> 테라

드봉 -> 드봉

릴리 -> 릴리

리엔자 -> 리엔자

코팅 -> 코팅

파르텔 -> 파르텔

사랑 -> 사랑

어벤 -> 어벤

중형 -> 중형

대형 -> 대형

특대 -> 특대

푸드 -> 푸드

쉐프원 -> 쉐프원

안주 -> 안주

안주야 -> 안주야

맛선 -> 맛선

맛선생 -> 맛선생

카레여 -> 카레여

카레여왕 -> 카레여왕

대상 -> 대상

호밍 -> 호밍

호밍스 -> 호밍스

비스 -> 비스

마시는 -> 마시는

청우 -> 청우

초이 -> 초이

초이스 -> 초이스

네슬 -> 네슬

네슬레 -> 네슬레

네스 -> 네스

네스카 -> 네스카

네스카페 -> 네스카페

애견 -> 애견

칸타 -> 칸타

칸타타 -> 칸타타

트로피카 -> 트로피카

트로피카나 -> 트로피카나

펩시 -> 펩시

롯데스 -> 롯데

립톤 -> 립톤

카페라 -> 카페라

카페라떼 -> 카페라떼

롯데마 -> 롯데

롯데아 -> 롯데

요하 -> 요하

롯자 -> 롯자

말랑 -> 말랑

왓따 -> 왓따

목캔 -> 목캔

목캔디 -> 목캔디

크런키 -> 크런키

찰떡 -> 찰떡

리락 -> 리락

리락쿠 -> 리락쿠

리락쿠마 -> 리락쿠마

치토 -> 치토

치토스 -> 치토스

롯데크 -> 롯데

도리 -> 도리

도리토 -> 도리토

롯데가 -> 롯데

롯가 -> 롯가

롯가나 -> 롯가나

헬스 -> 헬스

롯데자 -> 롯데

롯데자일 -> 롯데

롯데자일리 -> 롯데

롯데자일리톨 -> 롯데

애니타 -> 애니타

월드콘 -> 월드

롯데크런 -> 롯데

쌀로 -> 쌀로

쌀로별 -> 쌀로별

프린세 -> 프린세

프린세스 -> 프린세스

아이디 -> 아이

마블 -> 마블

소피 -> 소피

누크 -> 누크

설레 -> 설레

설레임 -> 설레임

겨울왕 -> 겨울

겨울왕국 -> 겨울왕국

파워에 -> 파워

핸디 -> 핸디

아이러 -> 아이

유동 -> 유동

대림 -> 대림

오양 -> 오양

한성 -> 한성

모나 -> 모나

예감 -> 예감

에프 -> 에프

삼립 -> 삼립

훼미 -> 훼미

훼미리 -> 훼미리

필라 -> 필라

프렌치카 -> 프렌치카

프렌치카페 -> 프렌치카페

마키 -> 마키

불가 -> 불가

불가리 -> 불가리

불가리스 -> 불가리스

삼양라 -> 삼양

삼양라면 -> 삼양라면

천하 -> 천하

마미 -> 마미

켈로 -> 켈로

켈로그 -> 켈로

환타 -> 환타

파워에이 -> 파워에이

파워에이드 -> 파워에이드

미닛 -> 미닛

미닛메 -> 미닛메

미닛메이 -> 미닛메이

미닛메이드 -> 미닛메이드

조지 -> 조지

조지아 -> 조지아

글라 -> 글라

데미소 -> 데미소

데미소다 -> 데미소다

오란 -> 오란

오란씨 -> 오란씨

요맘 -> 요맘

요맘때 -> 요맘때

투게 -> 투게

투게더 -> 투게더

써니 -> 써니

써니텐 -> 써니텐

코코팜 -> 코코팜

미니쉘 -> 미니

마이쮸 -> 마이쮸

산도 -> 산도

소가 -> 소가

자연은 -> 자연

에쎄 -> 에쎄

보루 -> 보루

던힐 -> 던힐

꼬북 -> 꼬북

마켓 -> 마켓

마켓오 -> 마켓오

다이제 -> 다이제

고래 -> 고래

고래밥 -> 고래밥

닥터유 -> 닥터

포카칩 -> 포카칩

스윙 -> 스윙

스윙칩 -> 스윙칩

와우 -> 와우

구구 -> 구구

필라이 -> 필라이

필라이트 -> 필라이트

매일우 -> 매일

매일바 -> 매일

매일바이 -> 매일

매일바이오 -> 매일바이오

푸르 -> 푸르

푸르밀 -> 푸르밀

의성마 -> 의성마

의성마늘 -> 의성마늘

깨끗한나 -> 깨끗한나

깨끗한나라 -> 깨끗한나라

팔도 -> 팔도

머거 -> 머거

머거본 -> 머거본

삼육검 -> 삼육검

삼육검은 -> 삼육검은

옥시크 -> 옥시

옥시크린 -> 옥시

냄새하 -> 냄새

냄새하마 -> 냄새

에어윅 -> 에어윅

옥시싹 -> 옥시

옥시싹싹 -> 옥시

파워크 -> 파워

파워크린 -> 파워크린

냄새먹는하 -> 냄새

냄새먹는하마 -> 냄새

데톨핸 -> 데톨핸

데톨핸드 -> 데톨핸드

소와 -> 소와

몽고 -> 몽고

크리넥 -> 크리넥

크리넥스 -> 크리넥스

스카트 -> 스카트

디펜드 -> 디펜드

좋은느낌울 -> 좋은

화이트시 -> 화이트

화이트시크 -> 화이트

화이트시크릿 -> 화이트

코텍 -> 코텍

애니데 -> 애니데

애니데이 -> 애니데이

하기스매 -> 하기스

하기스매직 -> 하기스매직

하기스매직팬 -> 하기스매직팬

하기스매직팬티 -> 하기스매직팬티

하기스프 -> 하기스

하기스프리 -> 하기스

그린핑 -> 그린

그린핑거 -> 그린

말보로 -> 말보로

버지니 -> 버지니

버지니아 -> 버지니아

태화 -> 태화

국제 -> 국제

파스퇴 -> 파스퇴

파스퇴르 -> 파스퇴르

대한 -> 대한

접착 -> 접착

형광 -> 형광

모나리 -> 모나리

모나리자 -> 모나리자

무선 -> 무선

아크릴 -> 아크릴

화일 -> 화일

초등 -> 초등

캐릭 -> 캐릭

캐릭터 -> 캐릭터

단지 -> 단지

굿프 -> 굿프

모던 -> 모던

스티 -> 스티

반짝 -> 반짝

시스 -> 시스

실버 -> 실버

크린랩 -> 크린

크린랲 -> 크린

순수한면 -> 순수한면

릴리안 -> 릴리

삼부 -> 삼부

삼부자 -> 삼부자

에프킬 -> 에프킬

에프킬라 -> 에프킬라

산도깨 -> 산도깨

산도깨비 -> 산도깨비

웅진 -> 웅진

웅진자 -> 웅진

웅진자연 -> 웅진

던힐파 -> 던힐

던힐파인 -> 던힐

던힐파인컷 -> 던힐

참맛 -> 참맛

고려 -> 고려

움트 -> 움트

움트리 -> 움트리

팔리 -> 팔리

팔리아 -> 팔리아

팔리아멘 -> 팔리아멘

팔리아멘트 -> 팔리아멘트

코멕 -> 코멕

코멕스 -> 코멕스

히츠 -> 히츠

초야 -> 초야

뚜레 -> 뚜레

뚜레반 -> 뚜레반

우일 -> 우일

씽크대 -> 씽크

해뜨 -> 해뜨

해뜨락 -> 해뜨락

올찬 -> 올찬

리빙 -> 리빙

아트존 -> 아트존

또봇 -> 또봇

대원 -> 대원

글라스 -> 글라스

디즈 -> 디즈

디즈니 -> 디즈니

담터 -> 담터

과일나라 -> 과일

신사 -> 신사

송학 -> 송학

그루 -> 그루

흡착 -> 흡착

삼진 -> 삼진

한울 -> 한울

대영 -> 대영

맛고을 -> 맛고을

키친아 -> 키친아

키친아트 -> 키친아트

키아 -> 키아

풍년 -> 풍년

세신 -> 세신

퀸센 -> 퀸센

퀸센스 -> 퀸센스

광동 -> 광동

해피홈 -> 해피

리체 -> 리체

리체나 -> 리체나

챕스 -> 챕스

챕스틱 -> 챕스틱

아이깨 -> 아이

아이깨끗 -> 아이

아이깨끗해 -> 아이깨끗해

시스테 -> 시스테

시스테마 -> 시스테마

프레시팝 -> 프레시팝

성경 -> 성경

글라스락 -> 글라스락

댕기 -> 댕기

꽃남 -> 꽃남

꽃을 -> 꽃을

꽃을든 -> 꽃을든

꽃을든남 -> 꽃을든남

꽃을든남자 -> 꽃을든남자

홈키 -> 홈키

홈키파 -> 홈키파

컴배 -> 컴배

컴배트 -> 컴배트

홈매 -> 홈매

홈매트 -> 홈매트

브레프 -> 브레프

존쿡 -> 존쿡

쏘피 -> 쏘피

귀애 -> 귀애

귀애랑 -> 귀애랑

유피 -> 유피

손수 -> 손수

도그썬 -> 도그썬

신광 -> 신광

들국 -> 들국

들국화 -> 들국화

크린센 -> 크린

크린센스 -> 크린센스

스타킹 -> 스타킹

그루머 -> 그루머

예지 -> 예지

예지미 -> 예지미

예지미인 -> 예지미인

수드 -> 수드

수드림 -> 수드림

달인 -> 달인

잘풀 -> 잘풀

잘풀리 -> 잘풀리

잘풀리는 -> 잘풀리는

잘풀리는집 -> 잘풀리는집

아워 -> 아워

아워홈 -> 아워홈

마루오 -> 마루오

액티비 -> 액티비

액티비아 -> 액티비아

라베 -> 라베

수입돼 -> 수입

수입돼지 -> 수입돼지

해태구 -> 해태

해태구운 -> 해태

롯자일 -> 롯자일

롯빼 -> 롯빼

롯빼빼 -> 롯빼빼

롯빼빼로 -> 롯빼빼로

라베스 -> 라베스

라베스트 -> 라베스트

페러 -> 페러

페러스 -> 페러스

In [115]:
from collections import defaultdict
import sys
import numpy as np

class CohesionProbability:
    
    def __init__(self, max_l_length=10, min_count=30):
        self.max_l_length = max_l_length
        self.min_count = min_count
        self.L = {}
        
    def train(self, sents):
        for num_sent, sent in enumerate(sents):
            if num_sent % 5000 == 0:
                sys.stdout.write('\rinserting %d sents... ' % num_sent)
            for token in sent.split():
                for e in range(1, min(self.max_l_length, len(token)) + 1):
                    subword = token[:e]
                    self.L[subword] = self.L.get(subword,0) + 1
        print('\rinserting subwords into L: done')
        print('num subword = %d' % len(self.L))

        self.L = {subword:freq for subword, freq in self.L.items() if freq >= self.min_count}
        print('num subword = %d (after pruning with min count %d)' % (len(self.L), self.min_count))
    
    def get_cohesion(self, word):

        # 글자가 아니거나 공백, 혹은 희귀한 단어인 경우
        if (not word) or ((word in self.L) == False): 
            return 0.0

        if len(word) == 1:
            return 1.0

        word_freq = self.L.get(word, 0)
        base_freq = self.L.get(word[:1], 0)

        if base_freq == 0:
            return 0.0
        else:
            return np.power((word_freq / base_freq), 1 / (len(word) - 1))

In [116]:
my_cohesion_dict = {
    '블루베리' : 0.7,
    '블루' : 0.45
}

def L_tokenize_w_tolerance(word, tolerance=0.1):
    if len(word) <= 2:
        return word
    
    scores = []
    for e in range(2, min(len(word), max_l_length)+1):
        subword = word[:e]
        scores.append((subword, my_cohesion_dict.get(subword, 0))) # (word, cohesion)
        
    max_score = max([score for subword, score in scores])
    scores = [(subword, score) for (subword, score) in scores if (max_score - score) <= tolerance]
    
    return sorted(scores, key=lambda x:len(x[0]), reverse=True)[0][0]

for word in ['블루베']:
    print('w tolerance : %s -> %s'%(word, L_tokenize_w_tolerance(word, tolerance=0)))
    print('wo tolerance : %s -> %s'%(word, L_tokenize_w_tolerance(word)))

w tolerance : 블루베 -> 블루
wo tolerance : 블루베 -> 블루

In [117]:
max_l_length = 10
min_count = 30

In [118]:
for num_doc, doc in enumerate(corpus):
    if num_doc >= 3: break
    print("%s ...\n"%doc[:100])

GDS_NM ...

배송비 ...

사은행사쿠폰 ...

In [119]:
corpus.iter_sent = True
cohesion_probability = CohesionProbability()
cohesion_probability.train(corpus)

inserting subwords into L: done
num subword = 368670
num subword = 1960 (after pruning with min count 30)

In [121]:
for word in ['오레', '오레오', '블루', '블루베', '블루베리', '옥수', '옥수수' ]:
    if not word:
        print()
        continue
        
    print("%s = %.3f"%(word, cohesion_probability.get_cohesion(word)))

오레 = 0.012
오레오 = 0.106
블루 = 0.489
블루베 = 0.474
블루베리 = 0.608
옥수 = 0.352
옥수수 = 0.594

In [122]:
corpus = Corpus(corpus_fname, iter_sent=True)
len(corpus)

118052

In [123]:
max_l_length = 6
max_r_length = 5
min_count = 30

In [124]:
from collections import defaultdict
import sys

L = defaultdict(lambda : defaultdict(lambda: 0)) # 어린 -> 어린이
R = defaultdict(lambda : defaultdict(lambda: 0)) # 어린이 <- 린이

for num_sent, sent in enumerate(corpus):
    if num_sent % 5000 == 0:
        sys.stdout.write('\rinserting %d sents...'%num_sent)
        
    for token in sent.split():
        if len(token) < 2:
            continue
            
        for e in range(2, min(max_l_length, len(token)) + 1):
            subword_from = token[:e-1]
            subword_to = token[:e]
            L[subword_from][subword_to] += 1
            
        for b in range(2, min(max_r_length, len(token)) + 1):
            subword_from = token[-b+1:]
            subword_to = token[-b:]
            R[subword_from][subword_to] += 1
            
print('\ndone')

inserting 115000 sents...
done

In [125]:
def get_accessor_variety(word):
    # av_l : ?-린이
    # av_r : 어린-?
    av_l = 0 if not word in R else len(R[word])
    av_r = 0 if not word in L else len(L[word])
    return (av_l, av_r)

for word in ['오레', '오레오', '블루', '블루베', '블루베리', '옥수', '옥수수' ]:
    av = get_accessor_variety(word)
    print('%s\t(%d, %d)'%(word, av[0], av[1]))

오레	(5, 3)
오레오	(2, 16)
블루	(80, 41)
블루베	(0, 1)
블루베리	(90, 52)
옥수	(0, 1)
옥수수	(27, 50)

In [126]:
import numpy as np

def get_branching_entropy(word):
    def entropy(extensions):
        '''extensions: dict[str]: int
        '''
        sum_ = sum(extensions.values())
        if sum_ == 0:
            return 0
        
        entropy = 0
        for v in extensions.values():
            if v == 0: continue
            prob = v / sum_
            entropy += (prob * np.log(prob))
        return -1 * entropy

    # be_l: ?-린이
    # be_r: 어린-?

    be_l = 0 if not word in R else entropy(R[word])
    be_r = 0 if not word in L else entropy(L[word])    
    
    return (be_l, be_r)

for word in ['오레', '오레오', '블루', '블루베', '블루베리', '옥수', '옥수수' ]:
    be = get_branching_entropy(word)
    print('%s\t(%.3f, %.3f)' % (word, be[0], be[1]))

오레	(0.927, 0.254)
오레오	(0.693, 2.428)
블루	(3.928, 2.206)
블루베	(0.000, -0.000)
블루베리	(4.241, 3.779)
옥수	(0.000, -0.000)
옥수수	(2.712, 3.598)

In [127]:
cohesion_probability = CohesionProbability()
cohesion_probability.train(corpus)

inserting subwords into L: done
num subword = 368670
num subword = 1960 (after pruning with min count 30)

In [142]:
def cpbe_tokenize(word):
    if (not word) or (len(word) <= 2):
        return word
    
    score = []
    for e in range(2, min(len(word), max_l_length) + 1):
        subword = word[:e]
        be_l, be_r = get_branching_entropy(subword)
        cp_l = cohesion_probability.get_cohesion(subword)
        score.append((subword, cp_l * be_r, e)) # (word, cohesion * branching entropy, length)
        
    return sorted(score, key=lambda x:(x[1], x[1]), reverse=True)[0][0]

for word in ['오레', '오레오', '블루', '블루베', '블루베리', '옥수', '옥수수' ]:
    print('%s --> %s\n' % (word, cpbe_tokenize(word)))

오레 --> 오레

오레오 --> 오레오

블루 --> 블루

블루베 --> 블루

블루베리 --> 블루베리

옥수 --> 옥수

옥수수 --> 옥수수

## cohesion

In [84]:
from collections import defaultdict
count= defaultdict(lambda: 0)

for doc in docs:
    for word in doc.split():
        n = len(word)
        for e in range(1, n+1):
            count[word[:e]] += 1

def cohesion(w):
    return pow(count[w]/count[w[0]], 1/(len(w)-1))


def ltokenize(w):
    n = len(w)
    if n <= 2: 
        return (w, '') 
        tokens = []
    for e in range(2, n+1):
        tokens.append(w[:e], w[e:], cohesion(w[:e]))
    tokens = sorted(tokens, key=lambda x:-x[2])
    return tokens[0][:2]

In [86]:
!pip install soynlp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting soynlp
  Downloading soynlp-0.0.493-py3-none-any.whl (416 kB)
     |████████████████████████████████| 416 kB 7.3 MB/s
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from soynlp) (1.7.3)
Requirement already satisfied: psutil>=5.0.1 in /usr/local/lib/python3.7/dist-packages (from soynlp) (5.4.8)
Requirement already satisfied: numpy>=1.12.1 in /usr/local/lib/python3.7/dist-packages (from soynlp) (1.21.6)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.7/dist-packages (from soynlp) (1.0.2)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->soynlp) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.0->soynlp) (3.1.0)
Installing collected packages: soynlp
Successfully installed soynlp-0.0.493

In [100]:
from soynlp import DoublespaceLineCorpus
from soynlp.word import WordExtractor
from soynlp.tokenizer import LTokenizer
from gensim.models import Word2Vec

corpus = DoublespaceLineCorpus(corpus_fname, iter_sent=True)
word_extractor = WordExtractor()
word_extractor.train(corpus)
word_scores = word_extractor.extract()

cohesion_scores = {word:score.cohesion_forward for word, score in word_scores.items()}
ltokenizer = LTokenizer(scores = cohesion_scores)

word2vec_corpus = [ltokenizer.tokenize(sent) for sent in corpus]
word2vec = Word2Vec(word2vec_corpus)

training was done. used memory 2.891 Gb
all cohesion probabilities was computed. # words = 24822
all branching entropies was computed # words = 20389
all accessor variety was computed # words = 20389

In [108]:
word2vec.most_similar('사과')

[('롯데', 0.9993203282356262),
 ('대', 0.9991861581802368),
 ('중', 0.9991759061813354),
 ('기획', 0.9991738200187683),
 ('입', 0.9991567134857178),
 ('오뚜기', 0.9991472363471985),
 ('미니', 0.9991441965103149),
 ('치즈', 0.9991300106048584),
 ('오리온', 0.9990959167480469),
 ('초코', 0.9990220069885254)]

## word2vec

In [ ]:
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git
%cd Mecab-ko-for-Google-Colab
!bash install_mecab-ko_on_colab190912.sh

In [144]:
from tqdm import tqdm
from konlpy.tag import Mecab

In [145]:
mecab = Mecab()

In [146]:
f = open(path+'gds_word.txt', encoding="utf8")
lines = f.read().splitlines()
print(len(lines))

117562

In [149]:
result = []

for line in tqdm(lines):
  # 빈 문자열이 아닌 경우에만 수행
  if line:
    result.append(mecab.morphs(line))

100%|██████████| 117562/117562 [00:06<00:00, 18430.65it/s]

In [152]:
from gensim.models import Word2Vec
model = Word2Vec(result, size=100, window=5, min_count=5, workers=4, sg=0)

In [161]:
model_result1 = model.wv.most_similar("커피")
print(model_result1)

[('모카', 0.9501841068267822), ('라떼', 0.9462405443191528), ('가나', 0.9424690008163452), ('아이스', 0.9384410381317139), ('콜드', 0.9368197917938232), ('칸타타', 0.9360128045082092), ('아메리카노', 0.9338933229446411), ('카누', 0.9333361983299255), ('바닐라', 0.9289746880531311), ('조지아', 0.9289230108261108)]

## fasttext

In [ ]:
!pip install gensim

In [176]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import normalize
from sklearn.cluster import KMeans

k=2

# vectorizing
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(docs)

# L2 normalizing
X = normalize(X, norm='l2')

# training k-means
kmeans = KMeans(n_clusters=k).fit(X)

# trained labels and cluster centers
labels = kmeans.labels_
centers = kmeans.cluster_centers_

In [180]:
!pip install soyclustering

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting soyclustering
  Downloading soyclustering-0.2.0-py3-none-any.whl (28 kB)
Requirement already satisfied: numpy>=1.1 in /usr/local/lib/python3.7/dist-packages (from soyclustering) (1.21.6)
Installing collected packages: soyclustering
Successfully installed soyclustering-0.2.0

In [183]:
from scipy.io import mmread
x = mmread(gds_mer2).tocsr()

AttributeError: ignored