In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
path = '/content/drive/MyDrive/Colab Notebooks/Retail/data/'

In [ ]:
%%time
df = pd.read_csv(path+"통합.csv")

/usr/local/lib/python3.7/dist-packages/IPython/core/magics/execution.py:1310: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code, glob, local_ns)

CPU times: user 24.7 s, sys: 3.48 s, total: 28.2 s
Wall time: 30.9 s

In [ ]:
df

,PLU_CD,GDS_NM,SAL_DT,POS_NO,TRAN_NO,SALE_QTY,SALE_PRC,SALE_AMT,SCALES_GDS_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,마트명
0,2908990042063,*감자2kg/박스,20220929,R1,3,1.0,6950.0,6950.0,일반,20220929,180150.0,A마트
1,8801056002060,델몬트 망고,20220929,R1,3,1.0,3950.0,3950.0,일반,20220929,180150.0,A마트
2,8801068087130,삼립 56시간저온숙성숙,20220929,R1,3,1.0,2600.0,2600.0,일반,20220929,180150.0,A마트
3,8801111917476,크라운산도스윗밀크,20220929,R1,3,1.0,3350.0,3350.0,일반,20220929,180150.0,A마트
4,93682091,스니커즈피넛싱글,20201222,2,405,1.0,990.0,990.0,일반,20201222,202450.0,A마트
...,...,...,...,...,...,...,...,...,...,...,...,...
22757663,9300650432185,필라델피아크림200,20220811,01,253,1.0,5900.0,5900.0,일반,20220811,164837.0,P마트
22757664,9310022866104,위스카스/오션피쉬,20220902,02,452,1.0,10000.0,10000.0,일반,20220902,170319.0,P마트
22757665,9334214017686,시저)연어와쇠고기 1Kg,20220504,01,64,1.0,9900.0,9900.0,일반,20220504,71913.0,P마트
22757666,9334214017686,시저)연어와쇠고기 1Kg,20220829,02,558,1.0,9900.0,9900.0,일반,20220829,191831.0,P마트
22757667,9334214017686,시저)연어와쇠고기 1Kg,20220916,02,26,1.0,9900.0,9900.0,일반,20220915,222317.0,P마트

In [ ]:
# %%time
# df = df.sample(frac=0.1)

In [ ]:
df.head()

,PLU_CD,GDS_NM,SAL_DT,POS_NO,TRAN_NO,SALE_QTY,SALE_PRC,SALE_AMT,SCALES_GDS_TP_NM,REAL_SAL_DT,REAL_SAL_TTM,마트명
0,2908990042063,*감자2kg/박스,20220929,R1,3,1.0,6950.0,6950.0,일반,20220929,180150.0,A마트
1,8801056002060,델몬트 망고,20220929,R1,3,1.0,3950.0,3950.0,일반,20220929,180150.0,A마트
2,8801068087130,삼립 56시간저온숙성숙,20220929,R1,3,1.0,2600.0,2600.0,일반,20220929,180150.0,A마트
3,8801111917476,크라운산도스윗밀크,20220929,R1,3,1.0,3350.0,3350.0,일반,20220929,180150.0,A마트
4,93682091,스니커즈피넛싱글,20201222,2,405,1.0,990.0,990.0,일반,20201222,202450.0,A마트

## 칼럼 정리
- PLU_CD: 바코드(상품 카테고리 기준)
- GDS_NM: 상품 이름
- REAL_SAL_DT : 판매일자
- REAL_SAL_TTM: 시분초
- POS_NO: 포스 식별자
- TRAN_NO: 거래 식별자
- SALE_PRC: 개당 상품 가격
- SALE_QTY: 상품 개수 
- SALE_AMT: 매출액
*할인 등 적용
- SCALES_GDS_TP_NM: 일반/저울 상품
- SAL_DT: 일단 안씀

In [ ]:
# 16개 마트
df["마트명"].value_counts()

A마트    8903672
H마트    1968917
C마트    1881466
I마트    1764619
G마트    1707443
F마트    1619051
E마트     865789
B마트     819183
M마트     595251
O마트     594288
J마트     557402
N마트     444583
P마트     323561
L마트     317326
K마트     290155
D마트     104962
Name: 마트명, dtype: int64

In [ ]:
df.isna().sum()

PLU_CD              0
GDS_NM              0
SAL_DT              0
POS_NO              0
TRAN_NO             0
SALE_QTY            0
SALE_PRC            0
SALE_AMT            0
SCALES_GDS_TP_NM    0
REAL_SAL_DT         0
REAL_SAL_TTM        0
마트명                 0
dtype: int64

### 시간 칼럼 처리

In [ ]:
def time_column_preprocess(df):
    """시간 관련 칼럼 정리"""
    ttm_len = df["REAL_SAL_TTM"].astype(int).astype(str).apply(len)
    display(ttm_len.value_counts().sort_index())
    
    print(f"REAL_SAL_TTM 4글자 이하 제거: {(ttm_len <= 4).sum():,}")
    df = df[ttm_len >= 5]

    dt_col = df["REAL_SAL_DT"].astype(str) + df["REAL_SAL_TTM"].astype(int).astype(str).str.zfill(6)
    assert (dt_col.apply(len) != 14).sum() == 0
    df = df.assign(log_dt = pd.to_datetime(dt_col, format="%Y%m%d%H%M%S"))

    df = df.drop(["REAL_SAL_DT", "REAL_SAL_TTM", "SAL_DT"], axis=1)
    
    return df

In [ ]:
%%time
df = time_column_preprocess(df)

1          16
2         134
3        1358
4        4556
5     1027289
6    21724315
Name: REAL_SAL_TTM, dtype: int64

REAL_SAL_TTM 4글자 이하 제거: 6,064
CPU times: user 1min 9s, sys: 2.87 s, total: 1min 12s
Wall time: 1min 11s

In [ ]:
%%time
## 칼럼 정리 추가
df = df.drop(["POS_NO", "TRAN_NO"], axis=1)
df = df.rename(columns={"마트명":"mart_name"})

CPU times: user 699 ms, sys: 14.1 ms, total: 714 ms
Wall time: 711 ms

In [ ]:
df

,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,SCALES_GDS_TP_NM,mart_name,log_dt
0,2908990042063,*감자2kg/박스,1.0,6950.0,6950.0,일반,A마트,2022-09-29 18:01:50
1,8801056002060,델몬트 망고,1.0,3950.0,3950.0,일반,A마트,2022-09-29 18:01:50
2,8801068087130,삼립 56시간저온숙성숙,1.0,2600.0,2600.0,일반,A마트,2022-09-29 18:01:50
3,8801111917476,크라운산도스윗밀크,1.0,3350.0,3350.0,일반,A마트,2022-09-29 18:01:50
4,93682091,스니커즈피넛싱글,1.0,990.0,990.0,일반,A마트,2020-12-22 20:24:50
...,...,...,...,...,...,...,...,...
22757663,9300650432185,필라델피아크림200,1.0,5900.0,5900.0,일반,P마트,2022-08-11 16:48:37
22757664,9310022866104,위스카스/오션피쉬,1.0,10000.0,10000.0,일반,P마트,2022-09-02 17:03:19
22757665,9334214017686,시저)연어와쇠고기 1Kg,1.0,9900.0,9900.0,일반,P마트,2022-05-04 07:19:13
22757666,9334214017686,시저)연어와쇠고기 1Kg,1.0,9900.0,9900.0,일반,P마트,2022-08-29 19:18:31
22757667,9334214017686,시저)연어와쇠고기 1Kg,1.0,9900.0,9900.0,일반,P마트,2022-09-15 22:23:17

### 카테고리 매핑 정답지

In [ ]:
cate_map = pd.read_csv(path+"top3000_3.csv")
cate_raw = pd.read_excel(path+"리테일_카테고리_분류.xlsx")

In [ ]:
def cate_merge(cate_map, cate_raw):
    
    cate_map = cate_map[["GDS_NM", "대분류", "소분류"]]
    cate_map = cate_map.rename(columns={"대분류":"대", "소분류":"소"})

    cate_raw = cate_raw[["대", "소"]].drop_duplicates()
    cate_raw = cate_raw.assign(cate_id = range(len(cate_raw)))
    
    cate_df = cate_raw.merge(cate_map, on=["대", "소"], how="left")

    return cate_df

In [ ]:
cate_df = cate_merge(cate_map, cate_raw)

In [ ]:
len(cate_df.cate_id.unique())

1499

In [ ]:
cate_df.to_parquet(path+"category_map2.parquet")

In [ ]:
%%time
## 매핑
cate_map_dict = cate_df.dropna().set_index("GDS_NM").cate_id.to_dict()
df = df.assign(cate_id = df.GDS_NM.map(cate_map_dict))

CPU times: user 1.63 s, sys: 28.4 ms, total: 1.66 s
Wall time: 1.67 s

In [ ]:
df

,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,SCALES_GDS_TP_NM,mart_name,log_dt,cate_id
0,2908990042063,*감자2kg/박스,1.0,6950.0,6950.0,일반,A마트,2022-09-29 18:01:50,NaN
1,8801056002060,델몬트 망고,1.0,3950.0,3950.0,일반,A마트,2022-09-29 18:01:50,NaN
2,8801068087130,삼립 56시간저온숙성숙,1.0,2600.0,2600.0,일반,A마트,2022-09-29 18:01:50,NaN
3,8801111917476,크라운산도스윗밀크,1.0,3350.0,3350.0,일반,A마트,2022-09-29 18:01:50,609.0
4,93682091,스니커즈피넛싱글,1.0,990.0,990.0,일반,A마트,2020-12-22 20:24:50,NaN
...,...,...,...,...,...,...,...,...,...
22757663,9300650432185,필라델피아크림200,1.0,5900.0,5900.0,일반,P마트,2022-08-11 16:48:37,NaN
22757664,9310022866104,위스카스/오션피쉬,1.0,10000.0,10000.0,일반,P마트,2022-09-02 17:03:19,NaN
22757665,9334214017686,시저)연어와쇠고기 1Kg,1.0,9900.0,9900.0,일반,P마트,2022-05-04 07:19:13,NaN
22757666,9334214017686,시저)연어와쇠고기 1Kg,1.0,9900.0,9900.0,일반,P마트,2022-08-29 19:18:31,NaN
22757667,9334214017686,시저)연어와쇠고기 1Kg,1.0,9900.0,9900.0,일반,P마트,2022-09-15 22:23:17,NaN

In [ ]:
%%time
df.to_parquet(path+"df_preprocessed_3.parquet")

CPU times: user 7.86 s, sys: 753 ms, total: 8.61 s
Wall time: 8.79 s

In [ ]:
df.cate_id.isna().sum()/len(df.cate_id)

0.8619460412549375

In [ ]:
df

,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,SCALES_GDS_TP_NM,mart_name,log_dt,cate_id
0,2908990042063,*감자2kg/박스,1.0,6950.0,6950.0,일반,A마트,2022-09-29 18:01:50,NaN
1,8801056002060,델몬트 망고,1.0,3950.0,3950.0,일반,A마트,2022-09-29 18:01:50,NaN
2,8801068087130,삼립 56시간저온숙성숙,1.0,2600.0,2600.0,일반,A마트,2022-09-29 18:01:50,NaN
3,8801111917476,크라운산도스윗밀크,1.0,3350.0,3350.0,일반,A마트,2022-09-29 18:01:50,609.0
4,93682091,스니커즈피넛싱글,1.0,990.0,990.0,일반,A마트,2020-12-22 20:24:50,NaN
...,...,...,...,...,...,...,...,...,...
22757663,9300650432185,필라델피아크림200,1.0,5900.0,5900.0,일반,P마트,2022-08-11 16:48:37,NaN
22757664,9310022866104,위스카스/오션피쉬,1.0,10000.0,10000.0,일반,P마트,2022-09-02 17:03:19,NaN
22757665,9334214017686,시저)연어와쇠고기 1Kg,1.0,9900.0,9900.0,일반,P마트,2022-05-04 07:19:13,NaN
22757666,9334214017686,시저)연어와쇠고기 1Kg,1.0,9900.0,9900.0,일반,P마트,2022-08-29 19:18:31,NaN
22757667,9334214017686,시저)연어와쇠고기 1Kg,1.0,9900.0,9900.0,일반,P마트,2022-09-15 22:23:17,NaN

In [ ]:
df[df['cate_id'].notna()]

,PLU_CD,GDS_NM,SALE_QTY,SALE_PRC,SALE_AMT,SCALES_GDS_TP_NM,mart_name,log_dt,cate_id
3,8801111917476,크라운산도스윗밀크,1.0,3350.0,3350.0,일반,A마트,2022-09-29 18:01:50,609.0
20,8809420390171,팝콘강냉이,1.0,3750.0,3750.0,일반,A마트,2020-12-22 20:24:50,599.0
30,8801024053995,우리가족김밥단무지,1.0,2200.0,2200.0,일반,A마트,2020-12-23 10:46:19,507.0
85,201171,배추,1.0,2500.0,2500.0,일반,A마트,2020-12-31 18:07:15,87.0
86,201463,딸기,1.0,18000.0,18000.0,일반,A마트,2020-12-31 18:07:15,20.0
...,...,...,...,...,...,...,...,...,...
22755920,8809357185741,투명테이프,50.0,1500.0,75000.0,일반,P마트,2022-09-14 18:44:42,1147.0
22755921,8809357185741,투명테이프,1.0,1500.0,1500.0,일반,P마트,2022-09-13 23:18:13,1147.0
22755922,8809357185741,투명테이프,2.0,1500.0,3000.0,일반,P마트,2022-09-22 02:52:32,1147.0
22756932,8809688340031,도토리묵,2.0,900.0,1800.0,일반,P마트,2022-07-06 17:16:04,514.0
22756933,8809688340031,도토리묵,1.0,900.0,900.0,일반,P마트,2022-07-08 09:42:56,514.0

In [ ]:
cate_df

            대       소  cate_id       GDS_NM
0          과일      사과        0       양광사과7개
1          과일      사과        0           사과
2          과일      사과        0         홍로사과
3          과일      사과        0  봉지사과10입1봉행사
4          과일      사과        0       햇사과10개
...       ...     ...      ...          ...
3387  소형가전・공구    기타용품     1494          NaN
3388  소형가전・공구     소화기     1495          NaN
3389  소형가전・공구    호신용품     1496          NaN
3390  소형가전・공구     경보기     1497          NaN
3391  소형가전・공구  기타안전용품     1498          NaN

[3392 rows x 4 columns]

In [ ]:
len(cate_df.대.unique())

34